import { beforeEach, describe, expect, it, vi } from "vitest";
// US-35 : langue de la requête (cookie) : français dans ces tests.
vi.mock("@/lib/langue-serveur", async () => { const { textesDe } = await import("@/lib/textes"); return { getLangue: async () => "fr", getTextes: async () => textesDe("fr"), enLangue: async <T,>(r: T) => r }; });
import { modifierArticleServeur, publierArticleServeur } from "./actions";
const { boutique, publier, modifier, charger } = vi.hoisted(() => ({ boutique: vi.fn(), publier: vi.fn(), modifier: vi.fn(), charger: vi.fn() }));
vi.mock("@/lib/supabase/server", () => ({ creerClientServeur: async () => ({}) }));
vi.mock("@/lib/gestion-articles", () => ({ boutiqueDuCompte: boutique, modifierArticle: modifier, articleDeMaBoutique: charger }));
vi.mock("@/lib/publication-article", () => ({ publierArticle: publier }));
const saisie = { titre: "Polo", categorie: "T-shirts et polos", genre: "homme", couleur: "Bleu", description: "", prix: "3500", tailles: ["M"] };
const jpeg = (taille = 4) => new Blob([new Uint8Array([0xff, 0xd8, 0xff, ...new Array(Math.max(0, taille - 3)).fill(0)])], { type: "image/jpeg" });
function corps(changements = {}) { const c = new FormData(); c.set("saisie", JSON.stringify({ ...saisie, ...changements })); c.set("boutiqueId", "boutique"); c.set("id", "article"); c.set("tailles", JSON.stringify([{ libelle: "M", disponible: true }])); c.append("photos", jpeg(), "photo.jpg"); c.append("vignettes", jpeg(), "vignette.jpg"); return c; }
beforeEach(() => { vi.clearAllMocks(); boutique.mockResolvedValue("boutique"); publier.mockResolvedValue("article"); modifier.mockResolvedValue(undefined); charger.mockResolvedValue({ photos: [] }); });
describe("validation serveur des formulaires", () => {
  it("refuse une session absente et une boutique différente", async () => { boutique.mockRejectedValueOnce(new Error("Votre session a expiré.")); expect((await publierArticleServeur(corps())).erreur).toContain("session"); boutique.mockResolvedValue("autre"); expect((await publierArticleServeur(corps())).erreur).toContain("cette boutique"); expect(publier).not.toHaveBeenCalled(); });
  it.each([{ couleur: "Inconnue" }, { categorie: "Chaussures", tailles: ["M"] }, { genre: "enfant", tailles: ["M"] }])("refuse côté serveur les données invalides %j avant écriture", async changement => { expect((await publierArticleServeur(corps(changement))).erreur).toBeTruthy(); expect((await modifierArticleServeur(corps(changement))).erreur).toBeTruthy(); expect(publier).not.toHaveBeenCalled(); expect(modifier).not.toHaveBeenCalled(); });
  it("publie uniquement les JPEG reçus déjà compressés avec la boutique du compte", async () => { expect(await publierArticleServeur(corps())).toEqual({ id: "article" }); const compression = publier.mock.calls[0][4]; const f = publier.mock.calls[0][3][0]; expect(await compression(f)).toEqual({ photo: f, vignette: expect.any(File) }); expect(publier.mock.calls[0][1]).toBe("boutique"); });
  it("refuse un original PNG et plus de cinq photos", async () => { const c = corps(); c.delete("photos"); c.append("photos", new Blob(["p"], { type: "image/png" })); expect((await publierArticleServeur(c)).erreur).toContain("JPEG"); const trop = corps(); for (let i = 0; i < 5; i++) { trop.append("photos", jpeg()); trop.append("vignettes", jpeg()); } expect((await publierArticleServeur(trop)).erreur).toContain("5 photos"); expect(publier).not.toHaveBeenCalled(); });
  it("enregistre une modification et conserve les contrôles d’appartenance dans le service", async () => { const c = corps(); c.set("garder", '["existante"]'); expect(await modifierArticleServeur(c)).toEqual({ photos: [] }); expect(modifier).toHaveBeenCalledWith({}, "article", expect.any(Object), [{ libelle: "M", disponible: true }], { garder: ["existante"], fichiers: expect.any(Array) }, expect.any(Function)); });
  it("refuse un fichier annoncé JPEG dont les octets ne sont pas un JPEG", async () => { for (const faux of [new Blob(["<svg onload=alert(1)>"], { type: "image/jpeg" }), new Blob([new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])], { type: "image/jpeg" })]) { const c = corps(); c.delete("photos"); c.append("photos", faux, "p.jpg"); expect((await publierArticleServeur(c)).erreur).toContain("vrai fichier JPEG"); expect((await modifierArticleServeur(c)).erreur).toContain("vrai fichier JPEG"); } expect(publier).not.toHaveBeenCalled(); expect(modifier).not.toHaveBeenCalled(); });
  it("refuse plus de 4 Mo de photos et miniatures au total", async () => { const c = corps(); c.delete("photos"); c.delete("vignettes"); for (let i = 0; i < 3; i++) { c.append("photos", jpeg(1500 * 1024), "p.jpg"); c.append("vignettes", jpeg(), "v.jpg"); } expect((await publierArticleServeur(c)).erreur).toContain("4 Mo"); expect(publier).not.toHaveBeenCalled(); });
  it("exige une miniature JPEG réelle de moins de 150 Ko par photo", async () => {
    const sans = corps(); sans.delete("vignettes"); expect((await publierArticleServeur(sans)).erreur).toContain("miniature");
    const lourde = corps(); lourde.delete("vignettes"); lourde.append("vignettes", jpeg(151 * 1024), "v.jpg"); expect((await publierArticleServeur(lourde)).erreur).toContain("miniature");
    const fausse = corps(); fausse.delete("vignettes"); fausse.append("vignettes", new Blob(["<svg onload=alert(1)>"], { type: "image/jpeg" }), "v.jpg"); expect((await publierArticleServeur(fausse)).erreur).toContain("vrai fichier JPEG"); expect((await modifierArticleServeur(fausse)).erreur).toContain("vrai fichier JPEG");
    expect(publier).not.toHaveBeenCalled(); expect(modifier).not.toHaveBeenCalled();
  });
});
