import { beforeEach, describe, expect, it, vi } from "vitest";
import { modifierArticleServeur, publierArticleServeur } from "./actions";
const { boutique, publier, modifier, charger } = vi.hoisted(() => ({ boutique: vi.fn(), publier: vi.fn(), modifier: vi.fn(), charger: vi.fn() }));
vi.mock("@/lib/supabase/server", () => ({ creerClientServeur: async () => ({}) }));
vi.mock("@/lib/gestion-articles", () => ({ boutiqueDuCompte: boutique, modifierArticle: modifier, articleDeMaBoutique: charger }));
vi.mock("@/lib/publication-article", () => ({ publierArticle: publier }));
const saisie = { titre: "Polo", categorie: "Polos", genre: "homme", couleur: "Bleu", description: "", prix: "3500", tailles: ["M"] };
function corps(changements = {}) { const c = new FormData(); c.set("saisie", JSON.stringify({ ...saisie, ...changements })); c.set("boutiqueId", "boutique"); c.set("id", "article"); c.set("tailles", JSON.stringify([{ libelle: "M", disponible: true }])); c.append("photos", new Blob(["jpeg"], { type: "image/jpeg" }), "photo.jpg"); return c; }
beforeEach(() => { vi.clearAllMocks(); boutique.mockResolvedValue("boutique"); publier.mockResolvedValue("article"); modifier.mockResolvedValue(undefined); charger.mockResolvedValue({ photos: [] }); });
describe("validation serveur des formulaires", () => {
  it("refuse une session absente et une boutique différente", async () => { boutique.mockRejectedValueOnce(new Error("Votre session a expiré.")); expect((await publierArticleServeur(corps())).erreur).toContain("session"); boutique.mockResolvedValue("autre"); expect((await publierArticleServeur(corps())).erreur).toContain("cette boutique"); expect(publier).not.toHaveBeenCalled(); });
  it.each([{ couleur: "Inconnue" }, { categorie: "Chaussures", tailles: ["M"] }, { genre: "enfant", tailles: ["M"] }])("refuse côté serveur les données invalides %j avant écriture", async changement => { expect((await publierArticleServeur(corps(changement))).erreur).toBeTruthy(); expect((await modifierArticleServeur(corps(changement))).erreur).toBeTruthy(); expect(publier).not.toHaveBeenCalled(); expect(modifier).not.toHaveBeenCalled(); });
  it("publie uniquement les JPEG reçus déjà compressés avec la boutique du compte", async () => { expect(await publierArticleServeur(corps())).toEqual({ id: "article" }); const compression = publier.mock.calls[0][4]; const f = new File(["jpeg"], "p.jpg", { type: "image/jpeg" }); expect(await compression(f)).toBe(f); expect(publier.mock.calls[0][1]).toBe("boutique"); });
  it("refuse un original PNG et plus de cinq photos", async () => { const c = corps(); c.delete("photos"); c.append("photos", new Blob(["p"], { type: "image/png" })); expect((await publierArticleServeur(c)).erreur).toContain("JPEG"); const trop = corps(); for (let i = 0; i < 5; i++) trop.append("photos", new Blob(["p"], { type: "image/jpeg" })); expect((await publierArticleServeur(trop)).erreur).toContain("5 photos"); expect(publier).not.toHaveBeenCalled(); });
  it("enregistre une modification et conserve les contrôles d’appartenance dans le service", async () => { const c = corps(); c.set("garder", '["existante"]'); expect(await modifierArticleServeur(c)).toEqual({ photos: [] }); expect(modifier).toHaveBeenCalledWith({}, "article", expect.any(Object), [{ libelle: "M", disponible: true }], { garder: ["existante"], fichiers: expect.any(Array) }, expect.any(Function)); });
});
