import { useState } from "react";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import DescriptionArabe from "./DescriptionArabe";
import { TRADUCTION_INDISPONIBLE } from "@/lib/ia-traduction";
function Formulaire({ titre = "Polo bleu" }: { titre?: string }) { const [valeur, setValeur] = useState(""); return <DescriptionArabe titre={titre} description="Manches courtes." valeur={valeur} onChange={setValeur} />; }
beforeEach(() => vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: false, json: async () => ({ message: TRADUCTION_INDISPONIBLE }) })));
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
describe("zone arabe modifiable", () => {
  it("désactive la génération sans titre mais laisse la saisie manuelle disponible", () => { render(<Formulaire titre=" " />); expect((screen.getByRole("button") as HTMLButtonElement).disabled).toBe(true); const zone = screen.getByRole("textbox"); expect(zone.getAttribute("dir")).toBe("rtl"); expect(zone.getAttribute("lang")).toBe("ar"); fireEvent.change(zone, { target: { value: "نص يدوي" } }); expect((zone as HTMLTextAreaElement).value).toBe("نص يدوي"); });
  it("sans clé : affiche le message et conserve le texte modifiable", async () => { render(<Formulaire />); fireEvent.click(screen.getByRole("button", { name: "Générer en arabe" })); await waitFor(() => expect(screen.getByRole("status").textContent).toBe(TRADUCTION_INDISPONIBLE)); fireEvent.change(screen.getByRole("textbox"), { target: { value: "نص يدوي" } }); expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("نص يدوي"); });
  it("assemble la traduction simulée et permet de la corriger", async () => { vi.mocked(fetch).mockResolvedValue({ ok: true, json: async () => ({ titreAr: "قميص أزرق", descriptionAr: "أكمام قصيرة." }) } as Response); render(<Formulaire />); fireEvent.click(screen.getByRole("button", { name: "Générer en arabe" })); await waitFor(() => expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("قميص أزرق\nأكمام قصيرة.")); expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string)).toEqual({ titre: "Polo bleu", description: "Manches courtes." }); fireEvent.change(screen.getByRole("textbox"), { target: { value: "تصحيح يدوي" } }); expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("تصحيح يدوي"); });
  it("ne remplace pas une saisie effectuée pendant l’attente", async () => { let terminer!: (r: Response) => void; vi.mocked(fetch).mockImplementation(() => new Promise(resolve => { terminer = resolve; })); render(<Formulaire />); fireEvent.click(screen.getByRole("button")); fireEvent.change(screen.getByRole("textbox"), { target: { value: "نص محفوظ" } }); await act(async () => terminer({ ok: true, json: async () => ({ titreAr: "قميص", descriptionAr: "أكمام قصيرة." }) } as Response)); expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("نص محفوظ"); });
});
