import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import FormulaireArticle, { CHAMPS_ARTICLE_VIDES } from "./FormulaireArticle";
const enregistrer = vi.fn().mockResolvedValue(undefined);
beforeEach(() => { localStorage.clear(); enregistrer.mockClear(); vi.stubGlobal("URL", class extends URL { static createObjectURL() { return "blob:photo"; } static revokeObjectURL() {} }); vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: false, json: async () => ({ message: "IA indisponible" }) })); });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
const initial = { ...CHAMPS_ARTICLE_VIDES, titre: "Polo bleu", categorie: "T-shirts et polos", genre: "homme", prix: "3500", tailles: ["M"] };
const afficher = (ajout = false) => render(<FormulaireArticle initial={initial} cleBrouillon="test:brouillon" ajout={ajout} onEnregistrer={enregistrer} />);
describe("formulaire partagé ajout et modification", () => {
  it("sélectionne une seule couleur, conservée par son nom", async () => { afficher(); await act(async () => {}); fireEvent.click(screen.getByRole("button", { name: "Bleu" })); fireEvent.click(screen.getByRole("button", { name: "Rouge" })); expect(screen.getByRole("button", { name: "Bleu" }).getAttribute("aria-pressed")).toBe("false"); fireEvent.click(screen.getByRole("button", { name: "Enregistrer" })); await waitFor(() => expect(enregistrer).toHaveBeenCalledWith(expect.objectContaining({ couleur: "Rouge" }), [], false)); });
  it("retire les tailles incompatibles après une catégorie ou un genre différent", async () => { afficher(); await act(async () => {}); fireEvent.change(screen.getByRole("combobox", { name: "Catégorie" }), { target: { value: "Chaussures" } }); expect(screen.getByText("Tailles réinitialisées pour cette catégorie")).toBeTruthy(); expect(screen.queryByRole("button", { name: "M" })).toBeNull(); expect(screen.getByRole("button", { name: "35" })).toBeTruthy(); fireEvent.change(screen.getByRole("combobox", { name: "Genre" }), { target: { value: "enfant" } }); expect(screen.queryByRole("button", { name: "35" })).toBeNull(); expect(screen.getByRole("button", { name: "24" })).toBeTruthy(); expect(screen.queryByRole("textbox", { name: /Pointures/ })).toBeNull(); });
  it("affiche l’erreur en rouge, cible le premier champ et efface l’erreur dès correction", async () => { afficher(); await act(async () => {}); const titre = screen.getByRole("textbox", { name: "Titre" }); fireEvent.change(titre, { target: { value: "" } }); fireEvent.click(screen.getByRole("button", { name: "Enregistrer" })); expect(document.activeElement).toBe(titre); expect(titre.className).toContain("border-erreur"); expect(screen.getByRole("alert").className).toContain("text-erreur"); fireEvent.change(titre, { target: { value: "Chemise" } }); expect(titre.className).not.toContain("border-erreur"); expect(screen.queryByRole("alert")).toBeNull(); });
  it("ouvre le sélecteur avec un bouton type button, compte et retire les photos sans soumettre", async () => { afficher(); await act(async () => {}); const input = screen.getByLabelText("Choisir dans la galerie"); const clic = vi.spyOn(input, "click"); fireEvent.click(screen.getByRole("button", { name: "+ Ajouter des photos" })); expect(clic).toHaveBeenCalledOnce(); fireEvent.change(input, { target: { files: [new File(["a"], "a.jpg", { type: "image/jpeg" }), new File(["b"], "b.png", { type: "image/png" })] } }); expect(screen.getByText("2 / 5")).toBeTruthy(); expect(screen.getAllByRole("img")).toHaveLength(2); fireEvent.click(screen.getByRole("button", { name: "Retirer la photo 1" })); expect(screen.getByText("1 / 5")).toBeTruthy(); expect(enregistrer).not.toHaveBeenCalled(); });
  it("refuse plus de cinq photos et les fichiers non images", async () => { afficher(); await act(async () => {}); const input = screen.getByLabelText("Choisir dans la galerie"); fireEvent.change(input, { target: { files: Array.from({ length: 6 }, () => new File(["p"], "p.jpg", { type: "image/jpeg" })) } }); expect(screen.getByRole("alert").textContent).toContain("5 photos"); fireEvent.change(input, { target: { files: [new File(["p"], "p.pdf", { type: "application/pdf" })] } }); expect(screen.getByRole("alert").textContent).toContain("JPEG"); });
  it("restaure un brouillon sans photo, permet de l’effacer et supprime le brouillon après succès", async () => { localStorage.setItem("test:brouillon", JSON.stringify({ ...initial, titre: "Mon brouillon" })); afficher(); await screen.findByText(/Brouillon restauré/); expect((screen.getByRole("textbox", { name: "Titre" }) as HTMLInputElement).value).toBe("Mon brouillon"); expect(screen.getByText(/Les photos ne sont pas sauvegardées/)).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Effacer" })); expect(localStorage.getItem("test:brouillon")).toBeNull(); fireEvent.change(screen.getByRole("textbox", { name: "Titre" }), { target: { value: "Modification" } }); expect(localStorage.getItem("test:brouillon")).toContain("Modification"); fireEvent.click(screen.getByRole("button", { name: "Enregistrer" })); await waitFor(() => expect(localStorage.getItem("test:brouillon")).toBeNull()); });
  it("demande confirmation beforeunload uniquement si des modifications restent non enregistrées", async () => { afficher(); await act(async () => {}); expect(window.dispatchEvent(new Event("beforeunload", { cancelable: true }))).toBe(true); fireEvent.change(screen.getByRole("textbox", { name: "Titre" }), { target: { value: "Modification" } }); expect(window.dispatchEvent(new Event("beforeunload", { cancelable: true }))).toBe(false); fireEvent.click(screen.getByRole("button", { name: "Enregistrer" })); await waitFor(() => expect(window.dispatchEvent(new Event("beforeunload", { cancelable: true }))).toBe(true)); });
  it("reste utilisable si localStorage refuse la lecture et l’écriture", async () => { const lire = vi.spyOn(Storage.prototype, "getItem").mockImplementation(() => { throw new Error("privé"); }); const ecrire = vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => { throw new Error("plein"); }); afficher(); await act(async () => {}); fireEvent.change(screen.getByRole("textbox", { name: "Titre" }), { target: { value: "Mon polo" } }); fireEvent.click(screen.getByRole("button", { name: "Enregistrer" })); await waitFor(() => expect(enregistrer).toHaveBeenCalled()); lire.mockRestore(); ecrire.mockRestore(); });
});
