// US-23 : textes arabes (arabe simple, darja oranaise quand c'est plus naturel ; masculin générique).
// Les 10 textes de la story US-23 ont été validés par le propriétaire le 9/10/2026 : ils sont repris tels quels
// (marqués « validé »). Les autres suivent le même style.
import type { Textes } from "./fr";

export const ar: Textes = {
  entete: {
    navigation: "تصفح الموقع",
    rechercher: "ابحث",
    panier: "السلة",
    carte: "الخريطة", // US-24, texte 1
    panierUnArticle: "السلة (1)",
    panierArticles: "السلة ({n})",
  },
  langue: {
    groupe: "اللغة",
    autre: "FR",
    autreNom: "Français",
    autreCode: "fr",
  },
  erreur: {
    titre: "كاين مشكل", // validé
    reessayer: "عاود جرّب", // validé
  },
  introuvable: {
    titre: "هاد الصفحة ما كايناش",
    retour: "ارجع للصفحة الرئيسية",
  },
  listes: {
    univers: { femme: "نساء", homme: "رجال", enfant: "أطفال", beaute: "تجميل" },
    genres: { homme: "رجال", femme: "نساء", enfant: "أطفال", mixte: "للجميع" },
    groupesCategories: { mode: "لبسة", beaute: "تجميل" },
    categories: {
      "T-shirts et polos": "تيشيرتات وبولو",
      "Chemises": "قمجان",
      "Pulls et sweats": "تريكوات وسويتات",
      "Vestes et manteaux": "جاكيطات ومانطوات",
      "Pantalons et jeans": "سراول وجينز",
      "Survêtements et ensembles": "سورفيتات وأطقم",
      "Robes": "روبات",
      "Jupes": "جيبات",
      "Abayas, djellabas, kamis": "عبايات، جلابات، قمصان",
      "Tenues traditionnelles": "لبسة تقليدية",
      "Hijabs et foulards": "حجابات ومحارم",
      "Chaussures": "صبابط",
      "Sacs": "صاكات",
      "Accessoires": "إكسسوارات",
      "Parfums": "عطور",
      "Maquillage": "ماكياج",
      "Soins visage et corps": "العناية بالوجه والجسم",
      "Cheveux": "الشعر",
      "Hammam et traditionnel": "حمّام وتقليدي",
    },
    tailleUnique: "مقاس واحد",
  },
  accueil: {
    univers: "الأقسام",
    titre: "بروموات وهران",
    sousTitre: "احجز على واتساب · خلّص في الحانوت",
    voirPromos: "شوف التخفيضات", // validé
    creditPhoto: "الصورة:",
    lesUnivers: "الأقسام",
    piecesPhares: "أهم السلع",
    enCeMoment: "دابا",
    toutVoir: "شوف الكل",
    espaceCommercant: "فضاء التجار",
  },
  promos: {
    aucune: "ما كاين حتى تخفيض دابا. ارجع قريب تشوف الجديد.",
    chargement: "راهو يتحمّل…",
    erreurSuite: "ما قدرناش نحمّلو الباقي. عاود جرّب.",
    reessayer: "عاود جرّب",
    voirPlus: "شوف تخفيضات أخرى",
  },
  carte: {
    aucunePhoto: "ما كانش صورة",
    reduction: "\u2066−{n}%\u2069", // isolé de gauche à droite : « −30% » ne devient pas « 30%− »
  },
  catalogue: {
    titre: "كل السلع",
    rechercherArticle: "ابحث على سلعة",
    exemple: "بولو، جينز، روبة، عطر…",
    filtres: "الفلاتر",
    univers: "القسم",
    categorie: "النوع",
    toutes: "الكل",
    tous: "الكل",
    taille: "المقاس",
    genre: "لمن",
    quartier: "الحي",
    prixMin: "أقل سعر (دج)",
    prixMax: "أعلى سعر (دج)",
    enPromo: "غير اللي فيهم تخفيض",
    rechercher: "ابحث",
    effacer: "امسح الفلاتر",
    unResultat: "النتائج: {n}",
    resultats: "النتائج: {n}",
    aucun: "ما لقينا حتى سلعة. جرّب كلمات أخرى ولا امسح الفلاتر.",
    pagination: "صفحات الكتالوغ",
    precedent: "السابق",
    suivant: "التالي",
  },
  fiche: {
    retour: "رجوع",
    aucunePhoto: "ما كانش صورة",
    jusquAu: "حتى {date}",
    plusDisponible: "هاد السلعة ما بقاتش", // validé
    vendu: "هاد السلعة تباعت",
    autresArticles: "سلع أخرى من نفس الحانوت",
    aucunAutre: "ما كانش سلع أخرى دابا",
    photosDe: "صور {titre}",
    galerie: "معرض الصور",
    photoN: "{titre} — صورة {n} من {total}",
    photoPrecedente: "الصورة اللي قبل",
    photoSuivante: "الصورة اللي بعد",
    voirPhoto: "شوف الصورة {n}",
    photoSur: "صورة {n} من {total}",
    partager: "شارك",
    lienCopie: "الرابط تنسخ",
    partageImpossible: "ما قدرناش نشاركو الرابط.",
    taille: "المقاس",
    tailleN: "مقاس {taille}",
    tailleEpuisee: "مقاس {taille}، ما بقاش",
    choisirTaille: "اختار المقاس باش تطلب.",
    aucuneTaille: "ما كاين حتى مقاس دابا.",
    contenance: "الحجم",
    contenanceN: "الحجم {taille}",
    contenanceEpuisee: "{taille}، ما بقاش",
    choisirContenance: "اختار الحجم باش تطلب.",
    aucuneContenance: "ما كاين حتى حجم دابا.",
    quantite: "الكمية",
    quantiteN: "الكمية: {n}",
    moins: "نقّص وحدة",
    plus: "زيد وحدة",
    ajouter: "زيد للسلة", // validé
    ajoute: "تزادت للسلة.",
    voirPanier: "شوف السلة",
    viderEtAjouter: "فرّغ السلة وزيد",
    ajoutImpossible: "ما قدرناش نزيدو السلعة للسلة.",
    confirmation: "الحانوت يأكّد طلبك. الخلاص في الحانوت.", // « الخلاص في الحانوت » validé
    question: "عندك سؤال؟ واتساب",
  },
  signaler: {
    bouton: "بلّغ على هاد السلعة",
    motif: "علاش تبلّغ؟",
    choisir: "اختار السبب",
    contrefacon: "سلعة مقلّدة",
    contenuInapproprie: "محتوى ماشي لايق",
    arnaque: "تحايل",
    autre: "سبب آخر",
    commentaire: "تعليق (إذا حبيت)",
    envoi: "راهو يتبعث…",
    envoyer: "ابعث البلاغ",
    choisirMotif: "اختار السبب.",
    echec: "البلاغ ما تبعثش. عاود جرّب.",
  },
  vitrine: {
    partager: "شارك الحانوت",
    adresseInconnue: "العنوان ما كانش",
    horairesInconnus: "الأوقات ما كانش",
    whatsapp: "واتساب",
    itineraire: "الطريق",
    localisation: "بلاصة الحانوت",
    carte: "الخريطة: {nom}",
    itineraireVers: "الطريق إلى {nom}",
    articles: "السلع الموجودة · التخفيضات اللولين",
    aucun: "ما كاين حتى سلعة دابا.",
    indisponible: "الحانوت ما راهوش متوفر",
    retour: "ارجع للصفحة الرئيسية",
  },
  panier: {
    titre: "السلة ديالي",
    vide: "السلة فارغة.",
    voirArticles: "شوف السلع",
    articles: "السلع في السلة",
    photo: "صورة",
    tailleEtPrix: "مقاس {taille} · {prix}",
    contenanceEtPrix: "{taille} · {prix}",
    moins: "{titre} {taille}: نقّص وحدة",
    plus: "{titre} {taille}: زيد وحدة",
    retirer: "نحّي {titre} ({taille})",
    note: "كلمة للحانوت (إذا حبيت)",
    noteTropLongue: "الكلمة لازم ما تفوتش {max} حرف.",
    total: "المجموع",
    seConnecter: "ادخل لحسابك باش تطلب",
    verifierTitre: "أكّد رقمك باش تطلب",
    verifierTexte: "يجيك كود فيه 6 أرقام على واتساب. الحانوت يتصل بيك على هاد الرقم.",
    profilNom: "قبل أول طلب، اكتب اسمك.",
    profilNomTelephone: "قبل أول طلب، اكتب اسمك ورقم الواتساب ديالك.",
    enregistrerContinuer: "سجّل وكمّل",
    envoi: "راهو يتبعث…",
    commander: "اطلب", // validé
    envoiImpossible: "ما قدرناش نبعثو الطلب. عاود جرّب.",
    connexionPerdue: "ما قدرناش نبعثو الطلب. شوف الأنترنت ديالك وعاود جرّب.",
    mention: "الحانوت يأكّد طلبك · الخلاص في الحانوت · سلة وحدة لكل حانوت",
  },
  compte: {
    navigation: "حسابي",
    monCompte: "حسابي",
    monProfil: "معلوماتي",
    mesCommandes: "طلباتي",
    panier: "السلة",
    seDeconnecter: "اخرج",
    monEspace: "فضاء الحانوت ديالي",
    chargementImpossible: "ما قدرناش نحمّلو معلوماتك. عاود جرّب.",
    deconnexionImpossible: "ما قدرناش نخرجوك. عاود جرّب.",
  },
  profil: {
    nom: "الاسم واللقب",
    telephone: "رقم الواتساب",
    contact: "الحانوت يتصل بيك على هاد الرقم على جال طلبك.",
    enregistrer: "سجّل",
    enregistrement: "راهو يتسجّل…",
  },
  numero: {
    verifie: "الرقم مأكّد",
    changer: "بدّل الرقم",
    verifierTitre: "أكّد رقمك باش تطلب",
    verifierTexte: "نبعثولك كود فيه 6 أرقام على واتساب. الحانوت يتصل بيك على هاد الرقم.",
  },
  connexion: {
    titre: "ادخل لحسابك",
    sousTitre: "باش تطلب وتتبّع طلباتك",
    lienInvalide: "رابط الدخول هذا غالط، ولا فات وقتو، ولا تستعمل من قبل. اطلب رابط جديد.",
    avecEmail: "ادخل بالإيميل (حساب مسجّل بالإيميل)",
    avecNumero: "ادخل برقم التيليفون",
    email: "الإيميل",
    emailAide: "يجيك رابط باش تدخل بلا كلمة سر.",
    emailRecevoir: "ابعثلي رابط الدخول",
    envoi: "راهو يتبعث…",
    emailInvalide: "اكتب إيميل صحيح.",
    antiRobot: "أكّد بلي راك ماشي روبو قبل.",
    emailEnvoye: "بعثنالك رابط الدخول في الإيميل",
    emailImpossible: "ما قدرناش نبعثو رابط الدخول. عاود جرّب من بعد شوية.",
  },
  code: {
    numero: "رقم البورطابل",
    aide: "غير الأرقام الجزائرية (05، 06 ولا 07). يجيك كود فيه 6 أرقام على واتساب.",
    recevoir: "ابعثلي الكود على واتساب",
    envoi: "راهو يتبعث…",
    antiRobot: "أكّد بلي راك ماشي روبو لتحت قبل.",
    envoiImpossible: "ما قدرناش نبعثو الكود. شوف الأنترنت ديالك وعاود جرّب.",
    envoye: "الكود تبعث لـ {numero}.",
    code: "الكود (6 أرقام)",
    valider: "أكّد الكود",
    verification: "راهو يتأكّد…",
    changer: "بدّل الرقم ولا اطلب كود جديد",
    saisir: "اكتب الأرقام الستة اللي جاوك.",
    verificationImpossible: "ما قدرناش نتأكدو من الكود. شوف الأنترنت ديالك وعاود جرّب.",
  },
  commandes: {
    titre: "طلباتي",
    aucune: "ما عندك حتى طلب دابا.",
    voirArticles: "شوف السلع",
    chargementImpossible: "ما قدرناش نحمّلو طلباتك. عاود جرّب.",
    commandeImpossible: "ما قدرناش نحمّلو الطلب. عاود جرّب.",
    numero: "الطلب رقم {n}",
    statuts: { demandee: "تبعث", confirmee: "تأكّد", prete: "واجد", recuperee: "تدّا", annulee: "تلغى", expiree: "فات وقتو" },
    titresSuivi: { demandee: "الطلب تبعث", confirmee: "الحانوت أكّد الطلب", prete: "طلبك راهو واجد", recuperee: "الطلب تدّا", annulee: "الطلب تلغى", expiree: "الطلب فات وقتو" }, // « طلبك راهو واجد » validé
    motifs: { plus_en_stock: "السلعة كملت", boutique_indisponible: "الحانوت ما راهوش متوفر", client_a_annule: "الزبون لغاه", autre: "سبب آخر" },
    suivi: "تتبّع الطلب",
    aVenir: " (من بعد)",
    aRecuperer: "روح تدّيه قبل",
    motif: "السبب: {motif}",
    expiree: "الطلب ما تدّاش في 24 ساعة: يتحسب ما جيتش.",
    articles: "السلع المطلوبة",
    total: "المجموع",
    note: "الكلمة ديالك: « {note} »",
    ecrire: "اكتب للحانوت على واتساب",
    voirBoutique: "شوف الحانوت",
    mention: "الخلاص في الحانوت · تقدر تلغي الطلب ما دام ماشي واجد",
    annuler: "الغي الطلب ديالي",
    motAnnulation: "كلمة للحانوت (إذا حبيت)",
    confirmerAnnulation: "أكّد الإلغاء",
    retour: "رجوع",
  },
  noShows: {
    titre: "طلبات ما تدّاوش ({n})",
    explication: "الحانوت قال بلي ما جيتش. إذا هاد الشي غالط، اعترض في {jours} أيام: الطلب ما يتحسبش حتى تقرر OranPromo (الحساب اللي راهو مبلوكي يبقى مبلوكي حتى للقرار). اعتراض واحد في المرة.",
    enExamen: "الاعتراض راهو يتشاف",
    refusee: "الاعتراض تّرفض: الطلب يتحسب",
    votreMotif: "السبب ديالك: {motif}",
    delaiDepasse: "فات وقت الاعتراض ({jours} أيام).",
    attendre: "تقدر تعترض على هادي كي تجاوبك OranPromo على الاعتراض اللي راهو يتشاف.",
    contester: "اعترض", // validé
    pourquoi: "علاش راك تعترض؟",
    envoi: "راهو يتبعث…",
    envoyer: "ابعث الاعتراض",
    fermer: "سكّر",
  },
  carteBoutiques: {
    // US-24.3 : textes de la carte proposés dans US-24 (gardés tels quels, relecture du propriétaire à venir).
    metaTitre: "خريطة الحوانت",
    titre: "الحوانت في الخريطة", // 2
    nombreUn: "{n} حانوت في وهران",
    nombre: "{n} حانوت في وهران",
    filtre: "اختار القسم",
    tous: "الكل", // 11
    univers: { femme: "نسا", homme: "رجال", enfant: "ذراري", beaute: "تجميل" }, // 11
    autourDeMoi: "قريب ليّا", // 3
    autourActif: "قريب ليّا · مفعّل",
    recherche: "راهو يقلّب على البلاصة نتاعك…",
    confidentialite: "البلاصة نتاعك تبقى في التيليفون نتاعك: ما تتبعثش وما تتسجّلش.", // 4
    refus: "ما عطيتش الإذن بالموقع: القائمة تبقى مرتّبة بالاسم.", // 10
    introuvable: "ما لقيناش البلاصة نتاعك دابا. عاود جرّب برّا ولا قريب من طاقة.",
    reessayer: "عاود جرّب",
    region: "خريطة حوانت وهران",
    vous: "أنت",
    indisponible: "الخريطة ما قدرتش تبان. قائمة الحوانت راهي لتحت.",
    promosUne: "{n} تخفيض دابا",
    promos: "{n} تخفيضات دابا", // 5
    aucunePromo: "ما كاين حتى تخفيض دابا",
    distance: "على بعد {d}", // 8
    voirBoutique: "شوف الحانوت", // 6
    itineraire: "الطريق", // 7
    fermer: "سكّر",
    listeParNom: "الحوانت · بالاسم",
    listeProches: "الحوانت · الأقرب هوما الأولين",
    sansPosition: "ما عندهمش بلاصة في الخريطة ({n})", // 9
    aucuneUnivers: "ما كاين حتى حانوت في هاد القسم دابا.",
    voirToutes: "شوف كل الحوانت",
    aucune: "ما كاين حتى حانوت في الخريطة دابا.",
    erreur: "ما قدرناش نحمّلو الحوانت. عاود جرّب.",
    accueilTitre: "الحوانت في الخريطة", // 12
    accueilTexte: "لقى التخفيضات قريب منك.",
    accueilLien: "شوف الخريطة", // 12
  },
};
