// US-23 : textes arabes (arabe simple, darja oranaise quand c'est plus naturel ; masculin générique).
// Les 10 textes de la story US-23 ont été validés par le propriétaire le 9/10/2026 : ils sont repris tels quels
// (marqués « validé »). Les autres suivent le même style.
import type { Textes } from "./fr";

export const ar: Textes = {
  entete: {
    navigation: "تصفح الموقع",
    rechercher: "ابحث",
    panier: "السلة",
    carte: "الخريطة", // US-24, texte 1
    panierUnArticle: "السلة (1)",
    panierArticles: "السلة ({n})",
    changerVille: "بدّل المدينة، المدينة دروك: {ville}",
  },
  villes: {
    metaTitre: "اختار مدينتك",
    titre: "اختار مدينتك",
    texte: "التخفيضات والحوانيت على حساب المدينة. تقدر تبدّلها وقتما حبيت.",
    localiser: "لقاني وين راني",
    recherche: "راني نحوّس على البلاصة تاعك…",
    confidentialite: "البلاصة تاعك تبقى في التيليفون: ما تتبعثش وما تتسجلش.",
    proche: "راك قريب من {ville}.",
    horsVilles: "مازال ما كاش حوانت BleDeal قريب منك: اختار مدينة من هنا.",
    introuvable: "ما لقيناش البلاصة تاعك: اختار مدينة من هنا.",
    inconnue: "هاد المدينة مازالت ما راهيش في BleDeal.",
    boutiqueUne: "{n} حانوت",
    boutiques: "{n} حانوت",
    liste: "المدن",
    actuelle: "المدينة دروك",
  },
  langue: {
    groupe: "اللغة",
    autre: "FR",
    autreNom: "Français",
    autreCode: "fr",
  },
  erreur: {
    titre: "كاين مشكل", // validé
    reessayer: "عاود جرّب", // validé
  },
  introuvable: {
    titre: "هاد الصفحة ما كايناش",
    retour: "ارجع للصفحة الرئيسية",
  },
  listes: {
    univers: { femme: "نساء", homme: "رجال", enfant: "أطفال", beaute: "تجميل" },
    genres: { homme: "رجال", femme: "نساء", enfant: "أطفال", mixte: "للجميع" },
    genresBeaute: { femme: "ليها", homme: "ليه", mixte: "للجوج" },
    raccourcisBeaute: { "Parfums": "عطور", "Maquillage": "ماكياج", "Soins visage et corps": "العناية", "Cheveux": "الشعر", "Hammam et traditionnel": "حمّام" },
    groupesCategories: { mode: "لبسة", beaute: "تجميل" },
    categories: {
      "T-shirts et polos": "تيشيرتات وبولو",
      "Chemises": "قمجان",
      "Pulls et sweats": "تريكوات وسويتات",
      "Vestes et manteaux": "جاكيطات ومانطوات",
      "Pantalons et jeans": "سراول وجينز",
      "Survêtements et ensembles": "سورفيتات وأطقم",
      "Robes": "روبات",
      "Jupes": "جيبات",
      "Abayas, djellabas, kamis": "عبايات، جلابات، قمصان",
      "Tenues traditionnelles": "لبسة تقليدية",
      "Hijabs et foulards": "حجابات ومحارم",
      "Chaussures": "صبابط",
      "Sacs": "صاكات",
      "Accessoires": "إكسسوارات",
      "Parfums": "عطور",
      "Maquillage": "ماكياج",
      "Soins visage et corps": "العناية بالوجه والجسم",
      "Cheveux": "الشعر",
      "Hammam et traditionnel": "حمّام وتقليدي",
    },
    tailleUnique: "مقاس واحد",
  },
  accueil: {
    univers: "الأقسام",
    titre: "بروموات {deVille}", // {deVille} : en arabe, le nom seul (« وهران »)
    sousTitre: "احجز على واتساب · خلّص في الحانوت",
    voirPromos: "شوف التخفيضات", // validé
    creditPhoto: "الصورة:",
    lesUnivers: "الأقسام",
    piecesPhares: "أهم السلع",
    enCeMoment: "دابا",
    toutVoir: "شوف الكل",
    espaceCommercant: "فضاء التجار",
  },
  promos: {
    aucune: "ما كاين حتى تخفيض دابا. ارجع قريب تشوف الجديد.",
    chargement: "راهو يتحمّل…",
    erreurSuite: "ما قدرناش نحمّلو الباقي. عاود جرّب.",
    reessayer: "عاود جرّب",
    voirPlus: "شوف تخفيضات أخرى",
  },
  carte: {
    aucunePhoto: "ما كانش صورة",
    reduction: "\u2066−{n}%\u2069", // isolé de gauche à droite : « −30% » ne devient pas « 30%− »
  },
  catalogue: {
    titre: "كل السلع",
    rechercherArticle: "ابحث على سلعة",
    exemple: "بولو، جينز، روبة، عطر…",
    filtres: "الفلاتر",
    univers: "القسم",
    categorie: "النوع",
    toutes: "الكل",
    tous: "الكل",
    taille: "المقاس",
    genre: "لمن",
    quartier: "الحي",
    prixMin: "أقل سعر (دج)",
    prixMax: "أعلى سعر (دج)",
    enPromo: "غير اللي فيهم تخفيض",
    rechercher: "ابحث",
    effacer: "امسح الفلاتر",
    unResultat: "النتائج: {n}",
    resultats: "النتائج: {n}",
    aucun: "ما لقينا حتى سلعة. جرّب كلمات أخرى ولا امسح الفلاتر.",
    aucunBeaute: "ما كاين حتى منتوج تجميل دابا.",
    aucunVille: "مازال ما كاش سلعة في {ville}.",
    contenance: "الحجم",
    pour: "لمن",
    tout: "كامل",
    categoriesBeaute: "أصناف التجميل",
    pagination: "صفحات الكتالوغ",
    precedent: "السابق",
    suivant: "التالي",
    tri: "رتّب",
    recents: "الجداد",
    mieuxNotees: "الأحسن في النقاط",
  },
  fiche: {
    retour: "رجوع",
    aucunePhoto: "ما كانش صورة",
    jusquAu: "حتى {date}",
    plusDisponible: "هاد السلعة ما بقاتش", // validé
    vendu: "هاد السلعة تباعت",
    autresArticles: "سلع أخرى من نفس الحانوت",
    aucunAutre: "ما كانش سلع أخرى دابا",
    photosDe: "صور {titre}",
    galerie: "معرض الصور",
    photoN: "{titre} — صورة {n} من {total}",
    photoPrecedente: "الصورة اللي قبل",
    photoSuivante: "الصورة اللي بعد",
    voirPhoto: "شوف الصورة {n}",
    photoSur: "صورة {n} من {total}",
    partager: "شارك",
    lienCopie: "الرابط تنسخ",
    partageImpossible: "ما قدرناش نشاركو الرابط.",
    taille: "المقاس",
    tailleN: "مقاس {taille}",
    tailleEpuisee: "مقاس {taille}، ما بقاش",
    choisirTaille: "اختار المقاس باش تطلب.",
    aucuneTaille: "ما كاين حتى مقاس دابا.",
    contenance: "الحجم",
    contenanceN: "الحجم {taille}",
    contenanceEpuisee: "{taille}، ما بقاش",
    choisirContenance: "اختار الحجم باش تطلب.",
    aucuneContenance: "ما كاين حتى حجم دابا.",
    quantite: "الكمية",
    quantiteN: "الكمية: {n}",
    moins: "نقّص وحدة",
    plus: "زيد وحدة",
    ajouter: "زيد للسلة", // validé
    ajoute: "تزادت للسلة.",
    voirPanier: "شوف السلة",
    viderEtAjouter: "فرّغ السلة وزيد",
    ajoutImpossible: "ما قدرناش نزيدو السلعة للسلة.",
    confirmation: "الحانوت يأكّد طلبك. الخلاص في الحانوت.", // « الخلاص في الحانوت » validé
    question: "عندك سؤال؟ واتساب",
  },
  signaler: {
    bouton: "بلّغ على هاد السلعة",
    motif: "علاش تبلّغ؟",
    choisir: "اختار السبب",
    contrefacon: "سلعة مقلّدة",
    contenuInapproprie: "محتوى ماشي لايق",
    arnaque: "تحايل",
    autre: "سبب آخر",
    commentaire: "تعليق (إذا حبيت)",
    envoi: "راهو يتبعث…",
    envoyer: "ابعث البلاغ",
    choisirMotif: "اختار السبب.",
    echec: "البلاغ ما تبعثش. عاود جرّب.",
  },
  vitrine: {
    partager: "شارك الحانوت",
    adresseInconnue: "العنوان ما كانش",
    horairesInconnus: "الأوقات ما كانش",
    whatsapp: "واتساب",
    itineraire: "الطريق",
    localisation: "بلاصة الحانوت",
    carte: "الخريطة: {nom}",
    itineraireVers: "الطريق إلى {nom}",
    articles: "السلع الموجودة · التخفيضات اللولين",
    aucun: "ما كاين حتى سلعة دابا.",
    indisponible: "الحانوت ما راهوش متوفر",
    retour: "ارجع للصفحة الرئيسية",
  },
  // US-31.2 : textes arabes à faire valider par le propriétaire.
  suivre: {
    suivre: "تبّع",
    suivie: "✓ راك تتبّع",
    enCours: "لحظة…",
    confirmer: "ما تبقاش تتبّع {nom}؟",
    nePlusSuivre: "ما تبقاش تتبّع",
    garder: "خلّيها",
    mesBoutiques: "الحوانت نتاعي ({n})",
    titre: "الحوانت نتاعي",
    vide: "ما راك تتبّع حتى حانوت. اضغط « تبّع » في صفحة الحانوت باش تلقاه هنا.",
    voirCarte: "لقى حوانت",
    promos: "{n} تخفيضات دابا",
    unePromo: "تخفيض واحد دابا",
    aucunePromo: "ما كاين حتى تخفيض دابا",
    connexion: "ادخل لحسابك باش تتبّع الحانوت.",
    plafond: "راك تتبّع 200 حانوت: حبّس واحد باش تزيد آخر.",
    introuvable: "هاد الحانوت ما راهوش متوفر.",
    reserve: "غير حسابات الزبائن يقدرو يتبّعو الحوانت.",
    erreur: "ما قدرناش دابا. عاود جرّب.",
    bienvenueTitre: "مرحبا بيك عند {nom}",
    bienvenueTexte: "دير حسابك في BleDeal: تتبّع الحانوت وتحجز السلعة نتاعو من التيليفون، وتخلّص في الحانوت.",
    creerCompte: "دير حسابي",
    // US-31.4 : nouveaux, à valider.
    bonInscription: "بون مرحبا تاع {montant} كي تشري {minimum} ولا كثر، يخدم من غدوة في هاد الحانوت، ودروك في الحوانت الأخرين.", // à valider
    bonInscriptionNumero: "من بعد ما تأكّد النمرة نتاعك. تدّي بالـ QR code.", // à valider
    bonDonne: "بون مرحبا راهو في الحساب نتاعك، « البونات نتاعي ».", // à valider
    bonApresNumero: "أكّد النمرة نتاعك في الحساب باش يجيك بون مرحبا.", // à valider
  },
  // US-31.5 : textes arabes à faire valider par le propriétaire (n° 9 et 10 du module 17 ; les autres sont nouveaux).
  alertes: {
    vousSuivez: "راك تتبّع {nom}. تلقاه في الحساب نتاعك، « الحوانت نتاعي ».", // à valider
    caseAccord: "نحب يجيني على الواتساب البروموات الجداد تاع الحوانت اللي نتبّعهم (ميساج واحد في النهار على الأكثر). نقدر نحبّس وقتما حبيت.",
    enregistrer: "سجّل", // à valider
    enCours: "لحظة…",
    activees: "التنبيهات في الواتساب راهي خدّامة: ميساج واحد في النهار على الأكثر، كي يكون عند حانوت تتبّعو بروموات جداد.", // à valider
    pasDAlerte: "مليح: ما يجيك حتى تنبيه في الواتساب.", // à valider
    titre: "التنبيهات في الواتساب", // à valider
    etatActives: "خدّامين: ميساج واحد في النهار على الأكثر.", // à valider
    etatDesactivees: "محبوسين.", // à valider
    activer: "شعّل", // à valider
    desactiver: "حبّس", // à valider
    connexion: "ادخل لحسابك باش تتحكّم في التنبيهات.", // à valider
    nonProposees: "التنبيهات في الواتساب مازال ما كانوش.", // à valider
    erreur: "ما قدرناش دابا. عاود جرّب.",
    lienQuestion: "ما تحبش يجيوك على الواتساب البروموات الجداد تاع الحوانت اللي تتبّعهم؟", // à valider
    lienBouton: "ما نحبش", // à valider
    lienFait: "ما عادش يجيوك الميساجات.",
    lienToujours: "مازال راك تتبّع الحوانت نتاعك.", // à valider
    lienInvalide: "هاد الرابط ما يخدمش.", // à valider
    mesBoutiques: "الحوانت نتاعي",
  },
  panier: {
    titre: "السلة ديالي",
    vide: "السلة فارغة.",
    voirArticles: "شوف السلع",
    articles: "السلع في السلة",
    photo: "صورة",
    tailleEtPrix: "مقاس {taille} · {prix}",
    contenanceEtPrix: "{taille} · {prix}",
    moins: "{titre} {taille}: نقّص وحدة",
    plus: "{titre} {taille}: زيد وحدة",
    retirer: "نحّي {titre} ({taille})",
    note: "كلمة للحانوت (إذا حبيت)",
    noteTropLongue: "الكلمة لازم ما تفوتش {max} حرف.",
    total: "المجموع",
    seConnecter: "ادخل لحسابك باش تطلب",
    verifierTitre: "أكّد رقمك باش تطلب",
    verifierTexte: "يجيك كود فيه 6 أرقام على واتساب. الحانوت يتصل بيك على هاد الرقم.",
    profilNom: "قبل أول طلب، اكتب اسمك.",
    profilNomTelephone: "قبل أول طلب، اكتب اسمك ورقم الواتساب ديالك.",
    enregistrerContinuer: "سجّل وكمّل",
    envoi: "راهو يتبعث…",
    commander: "اطلب", // validé
    envoiImpossible: "ما قدرناش نبعثو الطلب. عاود جرّب.",
    connexionPerdue: "ما قدرناش نبعثو الطلب. شوف الأنترنت ديالك وعاود جرّب.",
    mention: "الحانوت يأكّد طلبك · الخلاص في الحانوت · سلة وحدة لكل حانوت",
  },
  compte: {
    navigation: "حسابي",
    monCompte: "حسابي",
    monProfil: "معلوماتي",
    mesCommandes: "طلباتي",
    panier: "السلة",
    seDeconnecter: "اخرج",
    monEspace: "فضاء الحانوت ديالي",
    chargementImpossible: "ما قدرناش نحمّلو معلوماتك. عاود جرّب.",
    deconnexionImpossible: "ما قدرناش نخرجوك. عاود جرّب.",
  },  // US-34.4 : « المعلومات نتاعي » (texte n° 8 de la conception) ; les autres textes sont nouveaux, à valider.
  donnees: {
    mesDonnees: "المعلومات نتاعي",
    intro: "واش تحفظ BleDeal على الحساب نتاعك، بالتواريخ.", // à valider
    numero: "النمرة",
    numeroVerifie: "{numero} · مأكّدة نهار {date}", // à valider
    numeroNonVerifie: "{numero} · ماشي مأكّدة", // à valider
    aucun: "ما كاينش",
    aucune: "ما كاينش",
    nom: "الاسم",
    compte: "الحساب",
    creeLe: "تحلّ نهار {date}", // à valider
    commandes: "الطلبات",
    bons: "البونات",
    avis: "الآراء",
    nombreDernier: "{n} · آخر واحد نهار {date}", // à valider
    nombreDerniere: "{n} · آخر واحد نهار {date}", // à valider
    boutiques: "الحوانت اللي تتبّعهم",
    suivieDepuis: "{nom} · من {date}", // à valider
    accords: "الموافقات", // à valider
    accord: "{document}، النسخة تاع {version} · قبلتها نهار {date}", // à valider
    droits: "نسخة، تصحيح، مسح ولا رفض: الحقوق نتاعك وكيفاش تطلبهم راهم في", // à valider
    lienPolitique: "سياسة الخصوصية",
    chargementImpossible: "ما قدرناش نحمّلو المعلومات نتاعك. عاود جرّب.",
    retour: "رجوع للحساب نتاعي",
  },

  profil: {
    nom: "الاسم واللقب",
    telephone: "رقم الواتساب",
    contact: "الحانوت يتصل بيك على هاد الرقم على جال طلبك.",
    enregistrer: "سجّل",
    enregistrement: "راهو يتسجّل…",
  },
  numero: {
    verifie: "الرقم مأكّد",
    changer: "بدّل الرقم",
    verifierTitre: "أكّد رقمك باش تطلب",
    verifierTexte: "نبعثولك كود فيه 6 أرقام على واتساب. الحانوت يتصل بيك على هاد الرقم.",
  },
  connexion: {
    titre: "ادخل لحسابك",
    sousTitre: "باش تطلب وتتبّع طلباتك",
    lienInvalide: "رابط الدخول هذا غالط، ولا فات وقتو، ولا تستعمل من قبل. اطلب رابط جديد.",
    avecEmail: "ادخل بالإيميل (حساب مسجّل بالإيميل)",
    avecNumero: "ادخل برقم التيليفون",
    email: "الإيميل",
    emailAide: "يجيك رابط باش تدخل بلا كلمة سر.",
    emailRecevoir: "ابعثلي رابط الدخول",
    envoi: "راهو يتبعث…",
    emailInvalide: "اكتب إيميل صحيح.",
    antiRobot: "أكّد بلي راك ماشي روبو قبل.",
    emailEnvoye: "بعثنالك رابط الدخول في الإيميل",
    emailImpossible: "ما قدرناش نبعثو رابط الدخول. عاود جرّب من بعد شوية.",
  },
  code: {
    numero: "رقم البورطابل",
    aide: "غير الأرقام الجزائرية (05، 06 ولا 07). يجيك كود فيه 6 أرقام على واتساب.",
    recevoir: "ابعثلي الكود على واتساب",
    envoi: "راهو يتبعث…",
    antiRobot: "أكّد بلي راك ماشي روبو لتحت قبل.",
    envoiImpossible: "ما قدرناش نبعثو الكود. شوف الأنترنت ديالك وعاود جرّب.",
    envoye: "الكود تبعث لـ {numero}.",
    code: "الكود (6 أرقام)",
    valider: "أكّد الكود",
    verification: "راهو يتأكّد…",
    changer: "بدّل الرقم ولا اطلب كود جديد",
    saisir: "اكتب الأرقام الستة اللي جاوك.",
    verificationImpossible: "ما قدرناش نتأكدو من الكود. شوف الأنترنت ديالك وعاود جرّب.",
  },
  commandes: {
    titre: "طلباتي",
    aucune: "ما عندك حتى طلب دابا.",
    voirArticles: "شوف السلع",
    chargementImpossible: "ما قدرناش نحمّلو طلباتك. عاود جرّب.",
    commandeImpossible: "ما قدرناش نحمّلو الطلب. عاود جرّب.",
    numero: "الطلب رقم {n}",
    statuts: { demandee: "تبعث", confirmee: "تأكّد", prete: "واجد", recuperee: "تدّا", annulee: "تلغى", expiree: "فات وقتو" },
    titresSuivi: { demandee: "الطلب تبعث", confirmee: "الحانوت أكّد الطلب", prete: "طلبك راهو واجد", recuperee: "الطلب تدّا", annulee: "الطلب تلغى", expiree: "الطلب فات وقتو" }, // « طلبك راهو واجد » validé
    motifs: { plus_en_stock: "السلعة كملت", boutique_indisponible: "الحانوت ما راهوش متوفر", client_a_annule: "الزبون لغاه", autre: "سبب آخر" },
    suivi: "تتبّع الطلب",
    aVenir: " (من بعد)",
    aRecuperer: "روح تدّيه قبل",
    motif: "السبب: {motif}",
    expiree: "الطلب ما تدّاش في 24 ساعة: يتحسب ما جيتش.",
    articles: "السلع المطلوبة",
    total: "المجموع",
    note: "الكلمة ديالك: « {note} »",
    ecrire: "اكتب للحانوت على واتساب",
    voirBoutique: "شوف الحانوت",
    mention: "الخلاص في الحانوت · تقدر تلغي الطلب ما دام ماشي واجد",
    annuler: "الغي الطلب ديالي",
    motAnnulation: "كلمة للحانوت (إذا حبيت)",
    confirmerAnnulation: "أكّد الإلغاء",
    retour: "رجوع",
  },
  retrait: {
    // US-26.2 : textes 1 à 10 de la story US-26 (darja en gras dans la story) ; les autres suivent le même style.
    bloc: "QR تاع الاستلام",
    consigne: "ورّي هاد QR للبيّاع في الحانوت. تخلّص تمّا، كاش.",
    sansCamera: "ما خدمتش الكاميرا؟ عطيه هاد الرقم تاع 6 أرقام:",
    aPayer: "تخلّص كاش",
    luminosite: "طلّع الضو تاع التيليفون باش يتقرا مليح.",
    envoyerProche: "ابعثو لواحد من دارك (واتساب)",
    copier: "كوبي الرابط",
    copie: "الرابط تكوبا.",
    copieImpossible: "ما قدرناش نكوبيو: ابعث الرابط في واتساب.",
    avertissement: "أي واحد عندو هاد الرابط يقدر يدّي الطلبية: ما تبعثوش غير لواحد تثيق فيه.",
    altQr: "QR تاع الاستلام، الطلبية رقم {n}",
    code: "رقم الاستلام",
    metaTitre: "طلبية للاستلام",
    titreProche: "الطلبية رقم {n} تدّيها من {boutique}",
    avant: "قبل {date}",
    consigneProche: "ورّي هاد QR للبيّاع، ولا عطيه الرقم تاع 6 أرقام:",
    voirBoutique: "شوف الحانوت",
    articles: "السلع اللي تدّيها",
    recuperee: "هاد الطلبية تدّات من قبل.",
    annulee: "هاد الطلبية تلغات: ما كاين والو باش تدّي.",
    expiree: "هاد الطلبية فات وقتها: ما بقاتش للاستلام.",
    invalide: "هاد الرابط ماشي صالح.",
    impossible: "ما قدرناش نجيبو الطلبية. عاود.",
  },
  noShows: {
    titre: "طلبات ما تدّاوش ({n})",
    explication: "الحانوت قال بلي ما جيتش. إذا هاد الشي غالط، اعترض في {jours} أيام: الطلب ما يتحسبش حتى تقرر BleDeal (الحساب اللي راهو مبلوكي يبقى مبلوكي حتى للقرار). اعتراض واحد في المرة.",
    enExamen: "الاعتراض راهو يتشاف",
    refusee: "الاعتراض تّرفض: الطلب يتحسب",
    votreMotif: "السبب ديالك: {motif}",
    delaiDepasse: "فات وقت الاعتراض ({jours} أيام).",
    attendre: "تقدر تعترض على هادي كي تجاوبك BleDeal على الاعتراض اللي راهو يتشاف.",
    contester: "اعترض", // validé
    pourquoi: "علاش راك تعترض؟",
    envoi: "راهو يتبعث…",
    envoyer: "ابعث الاعتراض",
    fermer: "سكّر",
  },
  carteBoutiques: {
    // US-24.3 : textes de la carte proposés dans US-24 (gardés tels quels, relecture du propriétaire à venir).
    metaTitre: "خريطة الحوانت",
    titre: "الحوانت في الخريطة", // 2
    nombreUn: "{n} حانوت في {ville}",
    nombre: "{n} حانوت في {ville}",
    filtre: "اختار القسم",
    tous: "الكل", // 11
    univers: { femme: "نسا", homme: "رجال", enfant: "ذراري", beaute: "تجميل" }, // 11
    autourDeMoi: "قريب ليّا", // 3
    autourActif: "قريب ليّا · مفعّل",
    recherche: "راهو يقلّب على البلاصة نتاعك…",
    confidentialite: "البلاصة نتاعك تبقى في التيليفون نتاعك: ما تتبعثش وما تتسجّلش.", // 4
    refus: "ما عطيتش الإذن بالموقع: القائمة تبقى مرتّبة بالاسم.", // 10
    introuvable: "ما لقيناش البلاصة نتاعك دابا. عاود جرّب برّا ولا قريب من طاقة.",
    reessayer: "عاود جرّب",
    region: "خريطة حوانت {deVille}",
    vous: "أنت",
    indisponible: "الخريطة ما قدرتش تبان. قائمة الحوانت راهي لتحت.",
    promosUne: "{n} تخفيض دابا",
    promos: "{n} تخفيضات دابا", // 5
    aucunePromo: "ما كاين حتى تخفيض دابا",
    distance: "على بعد {d}", // 8
    voirBoutique: "شوف الحانوت", // 6
    itineraire: "الطريق", // 7
    fermer: "سكّر",
    listeParNom: "الحوانت · بالاسم",
    listeProches: "الحوانت · الأقرب هوما الأولين",
    listeMieuxNotees: "الحوانت · الأحسن في النقاط هوما الأولين",
    mieuxNotees: "الأحسن في النقاط",
    sansPosition: "ما عندهمش بلاصة في الخريطة ({n})", // 9
    aucuneUnivers: "ما كاين حتى حانوت في هاد القسم دابا.",
    voirToutes: "شوف كل الحوانت",
    aucune: "ما كاين حتى حانوت في الخريطة دابا.",
    erreur: "ما قدرناش نحمّلو الحوانت. عاود جرّب.",
    accueilTitre: "الحوانت في الخريطة", // 12
    accueilTexte: "لقى التخفيضات قريب منك.",
    accueilLien: "شوف الخريطة", // 12
  },
  parrainage: {
    // US-27 : n° 1 à 4, 6 à 12 et 14 validés par le propriétaire (9/10) ; 5, 13, 15 à 24 et les autres textes : à relire.
    metaTitre: "العرضة",
    etiquette: "العرضة",
    titre: "عرّض صحابك", // 1
    intro: "عرّف صحابك بالتخفيضات تاع حوانيت مدينتك. كي صاحبك يدّي أول طلب من الحانوت، كل واحد فيكم يربح بون تاع 300 دج.",
    commentCaMarche: "كيفاش تخدم",
    etape1: "ابعث الرابط نتاعك لصحابك على واتساب.", // 2
    etape2: "صاحبك يتسجّل بنمرتو ويكتب نمرتك ولا الكود نتاعك.", // 3
    etape3: "كي يدّي أول طلب من الحانوت، تربحو بجوج.", // 4
    recompense: "بون تاع 300 دج لكل واحد، ينقص من الخلاص في الحانوت.", // 5
    tonCode: "الكود نتاعك",
    partagerWhatsApp: "ابعث على واتساب", // 6
    copierLien: "انسخ الرابط", // 7
    lienCopie: "الرابط تنسخ.",
    copieImpossible: "ما قدرناش ننسخو: ابعث الرابط على واتساب.",
    qrAlt: "QR تاع رابط العرضة نتاعك",
    qrTexte: "صاحبك يقدر يسكاني هاد QR بالتيليفون نتاعو. الرابط ما يبيّنش لا اسمك لا نمرتك.",
    connecteToi: "ادخل لحسابك باش تاخذ الرابط نتاعك",
    seConnecter: "ادخل",
    reserveClients: "العرضة غير للزبائن اللي نمرة الواتساب نتاعهم مأكّدة بالكود.",
    ferme: "العرضة مازال ما تحلّتش. ارجع من بعد!",
    bonTitre: "البون نتاعك تاع 300 دج",
    bonTexte: "في السلة، علّم على « خدم بالبون نتاعي »: تخلّص 300 دج أقل في الحانوت. BleDeal هي اللي تخلّص هاد 300 دج للحانوت.",
    voirMesBons: "شوف البونات نتاعي واللي عرضتهم",
    reglesTitre: "القواعد",
    regle1: "اللي عرض واللي تعرض، كل واحد نمرتو مأكّدة بكود الواتساب.",
    regle2: "ما تعرضش روحك. حساب واحد، واحد برك اللي عرضو.",
    regle3: "اللي تعرض يكتب اللي عرضو في 7 أيام، قبل أول طلب.",
    regle4: "البونات يجيو من بعد أول طلب تاع 2000 دج وفوق، يدّيه بالـ QR نتاعو، ماشي كي يتسجّل.",
    regle5: "البون صالح 60 يوم، واحد في كل طلب، من 1000 دج وفوق.",
    regle6: "5 صحاب في الشهر على الأكثر.",
    regle7: "BleDeal ما تكتب لحتى واحد من صحابك: انت اللي تبعث.",
    invite: "صاحبك عرضك لـ BleDeal", // 12
    inviteConnexion: "ادخل بنمرة الواتساب نتاعك، ومن بعد أكّد الكود تاع صاحبك.",
    tonParrain: "اللي عرضك",
    champ: "اللي عرضك (إلا حبيت): النمرة نتاع الواتساب ولا الكود", // 8
    rappel: "البون نتاعك ونتاع اللي عرضك يجيو من بعد أول طلب تاع 2000 دج وفوق، تدّيه من الحانوت بالـ QR نتاعك.", // 24
    valider: "أكّد",
    envoi: "راه يتبعث…",
    enregistre: "تسجّلت. إلا كانت هاد النمرة نتاع زبون في BleDeal، يولّي هو اللي عرضك من بعد أول طلب تدّيه من الحانوت.", // 9
    impossible: "ما قدرناش نسجّلو اللي عرضك. عاود جرّب.",
    parrainEnregistre: "اللي عرضك تسجّل",
    modifier: "بدّل",
    modificationsRestantes: "تقدر تبدّلو {n} مرات، قبل أول طلب.",
    monParrainage: "العرضة نتاعي",
    valides: "صحاب دّاو أول طلب", // 11
    valideUn: "صاحب دّا أول طلب",
    enAttente: "مازال ما دّاو أول طلب", // 11
    filleul: "{prenom} · {date}",
    bonFilleul: "بون تاع 300 دج",
    bonEnFile: "البون يستنّى (الميزانية)",
    plafond: "وصلت للحد تاع الشهر: 5 صحاب. اللي يجيو من بعد ياخذو البون نتاعهم، انت لا، حتى يكمل الشهر.",
    discretion: "الصحاب اللي مازال ما يبانوش بأسماءهم. حتى نمرة ما تبان.",
    aucunFilleul: "حتى صاحب مازال ما ربح: ابعث الرابط نتاعك.",
    commentMarche: "كيفاش تخدم العرضة؟",
    mesBons: "البونات نتاعي", // 15
    nomBon: "بون العرضة",
    disponible: "واجد · صالح حتى {date}", // 16
    reserve: "محجوز للطلب رقم {n}", // 21
    utilise: "تخدم نهار {date} عند {boutique}", // 22
    expire: "فات وقتو نهار {date}", // 23
    enFile: "البون نتاعك يجيك نهار {date} (الميزانية تاع الشهر كملت).", // 20
    annule: "تلغى",
    aideBons: "تخدم بيهم في السلة.", // à valider
    aideBonBleDeal: "{nom}: {montant} أقل، تخلّصو BleDeal.", // à valider
    aideBonInscription: "{nom}: {montant} أقل، تخلّصو BleDeal والحانوت اللي تسجّلت فيه.", // à valider
    accueilTitre: "عرّض صحابك", // 13
    accueilTexte: "300 دج لكل واحد", // 13
    accueilLien: "شوف",
    merciTitre: "يعطيك الصحة!", // 14
    merciTexte: "عرّف صاحبك بـ BleDeal: 300 دج لكل واحد من بعد أول طلب نتاعو.", // 14
    partagerMonLien: "ابعث الرابط نتاعي",
    utiliserBon: "خدم بالبون نتاعي (−{montant})", // 17
    ligneBon: "بون العرضة",
    aPayerBoutique: "تخلّص في الحانوت", // 18
    sousMinimum: "البون يخدم من 1000 دج وفوق.", // 19
    noteBon: "بون واحد في كل طلب. إلا الطلب تلغى ولا فات وقتو، البون يرجعلك.",
    // Vouvoiement du parrainage hors des pages du parrainage : en darja, la même forme (pas de différence tu/vous ici).
    vous: {
      tonParrain: "اللي عرضك",
      champ: "اللي عرضك (إلا حبيت): النمرة نتاع الواتساب ولا الكود",
      rappel: "البون نتاعك ونتاع اللي عرضك يجيو من بعد أول طلب تاع 2000 دج وفوق، تدّيه من الحانوت بالـ QR نتاعك.",
      impossible: "ما قدرناش نسجّلو اللي عرضك. عاود جرّب.",
      modificationsRestantes: "تقدر تبدّلو {n} مرات، قبل أول طلب.",
      copieImpossible: "ما قدرناش ننسخو: ابعث الرابط على واتساب.",
      qrAlt: "QR تاع رابط العرضة نتاعك",
      qrTexte: "صاحبك يقدر يسكاني هاد QR بالتيليفون نتاعو. الرابط ما يبيّنش لا اسمك لا نمرتك.",
      tonCode: "الكود نتاعك",
    },
    // US-33.2 : textes de la conception (module 19, n° 2, 9, 10) ; noteBonProgramme : nouveau, à valider.
    nomBienvenue: "بون مرحبا", // 2
    nomProgramme: "بون {nom}", // 5, 9
    detailProgramme: "{montant} كي تشري {minimum} ولا كثر · حتى {date}", // 2
    utiliserBonBienvenue: "استعمل بون مرحبا (−{montant})", // 9
    utiliserBonProgramme: "استعمل بون {nom} (−{montant})", // 9
    minimumProgramme: "كي تشري {minimum} ولا كثر", // 10
    noteBonProgramme: "بون واحد في كل طلب. إلا الحانوت لغات الطلب، البون يرجعلك؛ إلا لغيتو نتا ولا ما جيتش، البون يروح.", // à valider
    // US-33.3 : n° 3 à 8, 10 à 14 de la conception ; les autres sont nouveaux, à valider.
    jaiUnCode: "عندي كود", // 3
    ajouterCode: "زيد", // 4
    codeAjoute: "بون {nom} تزاد : {montant} كي تشري {minimum} ولا كثر.", // 5
    codeInconnu: "هاد الكود ما كاينش ولا فات الوقت نتاعو.", // 6
    codeDeja: "ديجا خذيت هاد البون.", // 7
    codeTrop: "بزاف تاع المحاولات. عاود من بعد ساعة.", // 8
    codeNumero: "أكّد النمرة نتاعك باش تزيد كود.", // à valider
    codeErreur: "ما قدرناش نزيدو هاد الكود. عاود جرّب.", // à valider
    raisonUnivers: "غير سلعة {univers}", // 11
    raisonVille: "ماشي في هاد المدينة", // 12
    raisonPlafond: "هاد البون ما بقاش يتقبل في هاد الحانوت لهاد البروموسيون.", // 13
    raisonBoutique: "هاد الحانوت ما بقاش ياخذ البونات", // à valider
    // US-31.4 : nouveaux, à valider.
    raisonPasAujourdhui: "في هاد الحانوت، من غدوة", // à valider
    detailInscription: "عند {boutique} : من {date}. في حوانت أخرين : دروك.", // à valider
    universBon: { femme: "النسا", homme: "الرجال", enfant: "الذراري", beaute: "التجميل" }, // « النسا » : n° 11 ; autres à valider
    bandeau: "{nom} : {montant} هدية كي تشري {minimum} ولا كثر بالكود {code}، حتى {date}.", // 14
    bandeauSansDate: "{nom} : {montant} هدية كي تشري {minimum} ولا كثر بالكود {code}.",
    conditionsCampagne: "الشروط", // 14
    conditionsTitre: "شروط بون {nom}", // à valider
    conditionsCode: "الكود : {code}", // à valider
    conditionsMontant: "{montant} هدية كي تشري {minimum} ولا كثر",
    conditionsVilles: "المدن : {villes}", // à valider
    conditionsToutesVilles: "في كامل المدن المفتوحة", // à valider
    conditionsDates: "من {debut} حتى {fin}", // à valider
    conditionsDepuis: "من {debut}", // à valider
    conditionsNumero: "مرة وحدة لكل نمرة مأكّدة.", // à valider
    conditionsQr: "لازم QR code باش تدّي من الحانوت.", // à valider
    conditionsAucune: "هاد البروموسيون ما كاينش ولا فات الوقت نتاعو.", // à valider
    bonNonApplique: {
      aucun_bon: "البون ما تحسبش: فات وقتو ولا ما بقاش. الطلب يبقى بالسومة الكاملة؛ تقدر تلغيه إلا حبيت.",
      minimum: "البون ما تحسبش: يخدم من 1000 دج وفوق. الطلب يبقى بالسومة الكاملة.",
      boutique_exclue: "البون ما تحسبش: هاد الحانوت ما يقبلش البونات دروك. الطلب يبقى بالسومة الكاملة؛ تقدر تلغيه إلا حبيت.",
      univers: "البون ما تحسبش: يخدم غير على شي سلعة. الطلب يبقى بالسومة الكاملة؛ تقدر تلغيه إلا حبيت.", // à valider
      ville: "البون ما تحسبش: ماشي في هاد المدينة. الطلب يبقى بالسومة الكاملة؛ تقدر تلغيه إلا حبيت.", // à valider
      plafond_boutique: "البون ما تحسبش: هاد البون ما بقاش يتقبل في هاد الحانوت لهاد البروموسيون. الطلب يبقى بالسومة الكاملة؛ تقدر تلغيه إلا حبيت.", // à valider
      pas_aujourdhui: "البون ما تحسبش: في الحانوت اللي تسجلت فيه، بون مرحبا يخدم من غدوة. الطلب يبقى بالسومة الكاملة؛ تقدر تلغيه إلا حبيت.", // à valider
      erreur: "البون ما تحسبش. الطلب يبقى بالسومة الكاملة؛ تقدر تلغيه إلا حبيت.",
    },
  },
  juridique: {
    piedDePage: "معلومات قانونية",
    conditions: "الشروط",
    commercants: "التجار",
    confidentialite: "الخصوصية",
    titres: {
      conditions: "شروط الاستعمال",
      conditions_commercants: "شروط التجار",
      confidentialite: "سياسة الخصوصية",
    },
    version: "النسخة تاع {date}",
    provisoire: "نسخة مؤقتة، راهي في المراجعة القانونية.",
    traductionAttente: "النص الرسمي هو النسخة بالفرنسية اللي تحت. الترجمة بالعربية تجي من بعد المراجعة القانونية.",
    caseInscription: "نقبل شروط الاستعمال وسياسة الخصوصية، حتى استعمال شركات برّا الدزاير (Supabase، Vercel، WhatsApp…).",
    caseRequise: "علّم على الخانة باش تدير الحساب نتاعك.",
    conditionsChangees: "الشروط نتاعنا تبدلو نهار {date}",
    accepterCommander: "نقبل ونطلب",
  },
  avis: {
    donner: "قول رايك",
    titre: "رايك في {boutique}",
    commande: "الطلب رقم {n}",
    note: "النقطة نتاعك",
    noteObligatoire: "النقطة لازم",
    etoiles: "{n} من 5",
    criteres: { accueil: "استقبال مليح", article_conforme: "السلعة كيما في الصورة", rapidite: "زربان" },
    commentaire: "كلمة (ماشي لازم)",
    compteur: "{n}/300",
    rappel: "رايك يبان للناس بإسمك والحرف الأول من لقبك.",
    publier: "انشر رايي",
    merci: "يعطيك الصحة، رايك تنشر.",
    noteRequise: "اختار نقطة من 1 حتى 5 نجوم.",
    donne: "عطيت رايك · ★ {note}",
    plusPossible: "تقدر تعطي رايك غير على طلب ديتو بالـ QR code نتاعك، في 14 يوم.",
    retourCommande: "رجوع للطلب",
    impossible: "ما قدرناش ننشرو رايك. عاود جرّب.",
    mentionBon: "الكليان ياخذو بون صغير على كل راي، مهما كانت النقطة.", // 11 (US-32.5)
    resume: "★ {note} · {n} راي",
    resumeFiche: "★ {note} ({n} راي)",
    pasAssez: "مازال ما كاينش بزاف تاع الآراء",
    titreSection: "آراء الكليان",
    noteSur: "{n} نجوم من 5",
    reponseBoutique: "رد الحانوت: {reponse}",
    voirTous: "شوف كامل الآراء",
    tousLesAvis: "الآراء على {boutique}",
    aucun: "مازال ما كاين حتى راي.",
    precedents: "آراء جداد",
    suivants: "آراء قدام",
    retourBoutique: "رجوع للحانوت",
    chargementImpossible: "ما قدرناش نحمّلو الآراء. عاود جرّب.",
    // US-32.4 : بلّغ على راي (النص 12 من الوحدة 18 ؛ الباقي : ترجمة لازم يصادق عليها المالك).
    signaler: "بلّغ",
    signalerTitre: "بلّغ على راي {auteur}",
    motifSignalement: "علاش تبلّغ؟",
    choisirMotif: "اختار السبب",
    motifs: { faux_avis: "راي ماشي صحيح", insulte: "سبّ ولا كلام ماشي لايق", informations_personnelles: "معلومات شخصية", autre: "سبب آخر" },
    commentaireSignalement: "تعليق (إذا حبيت)",
    envoyerSignalement: "ابعث البلاغ",
    envoiSignalement: "راهو يتبعث…",
    motifObligatoire: "اختار السبب.",
    signalementEchec: "البلاغ ما تبعثش. عاود جرّب.",
  },
  espace: {
    nav: {
      titre: "فضاء التاجر",
      mesArticles: "السلع نتاعي",
      commandes: "الطلبات",
      avis: "الآراء",
      avisSansReponse: "الآراء، {n} بلا رد",
      ajouter: "زيد",
      statistiques: "الإحصائيات",
      deconnecter: "اخرج",
    },
    commun: {
      monEspace: "الفضاء نتاعي",
      mesArticles: "السلع نتاعي",
      retourMesArticles: "→ السلع نتاعي",
      retourEspace: "رجوع للفضاء نتاعي",
      retourArticles: "رجوع للسلع نتاعي",
      sansBoutique: "الحساب نتاعك ماشي مربوط بحتى حانوت",
      profilImpossible: "ما قدرناش نحمّلو الحساب نتاعك. عاود جرّب.",
      enregistrement: "راهو يتسجّل…",
      retour: "رجوع",
      voir: "شوف",
      fermer: "سكّر",
      annuler: "الغي",
      scanner: "سكاني",
      copierLien: "انسخ الرابط",
      lienCopie: "الرابط تنسخ.",
    },
    accueil: {
      ajouterArticle: "+ زيد سلعة",
      articlesImpossible: "ما قدرناش نحمّلو السلع نتاعك. عاود جرّب.",
      deconnexionImpossible: "ما قدرناش نخرّجوك. عاود جرّب.",
      mesStatistiques: "الإحصائيات نتاعي",
      avisClients: "آراء الزبائن",
      avisClientsLibelle: "آراء الزبائن: {resume}",
      mesCommandes: "الطلبات نتاعي",
    },
    resumeAvis: {
      aucun: "مازال ما كاين حتى راي",
      nombre: "{n} راي",
      sansReponse: "{n} بلا رد",
    },
    abonnes: {
      titre: "الزبائن اللي يتبّعو الحانوت",
      aucun: "مازال حتى زبون ما يتبّع الحانوت نتاعك.",
      un: "زبون واحد يتبّع الحانوت نتاعك",
      plusieurs: "{n} زبائن يتبّعو الحانوت نتاعك",
      semaine: "{base} · +{n} هاد السيمانة",
      inscrit: "{base} · منهم {n} تسجّل في الحانوت",
      inscrits: "{base} · منهم {n} تسجّلو في الحانوت",
      bonsInscription: "بونات مرحبا تاع اللي تسجّلو هاد الشهر: {n}{plafond}.",
      part: " الحصة نتاعك: {montant} على كل بون يتخدم عندك (تتنقص من الخلاص).",
      affiche: "أفيش بـ QR code: سجّل الزبائن نتاعك في الكاشة",
    },
    articles: {
      aucun: "مازال ما عندك حتى سلعة.",
      statutImpossible: "ما قدرناش نبدّلو الحالة. عاود جرّب.",
      modifier: "بدّل {titre}",
      sansPhoto: "بلا صورة",
      promo: "تخفيض",
      statutDe: "حالة {titre}",
      statuts: {
        disponible: "كاينة",
        reserve: "محجوزة",
        vendu: "تباعت",
        masque: "مخبّية",
      },
      masqueModeration: "السلعة خبّاتها المراقبة: اتصل بالإدارة باش ترجع تبان.",
      stock: "السطوك",
      stockDe: "سطوك {titre}",
      moins: "مقاس {taille}: نقّص وحدة",
      plus: "مقاس {taille}: زيد وحدة",
      stockImpossible: "ما قدرناش نسجّلو السطوك. عاود جرّب.",
      epuise: "ما بقاش",
      piece: "حبة وحدة",
      pieces: "{n} حبات",
    },
    formulaire: {
      titre: "العنوان",
      titreAjout: "العنوان *",
      categorie: "النوع",
      categorieAjout: "النوع *",
      choisir: "اختار",
      genre: "لمن",
      genreAjout: "لمن",
      genreFacultatif: "لمن (إلا حبيت)",
      genreFacultatifAjout: "لمن (إلا حبيت)",
      nonPrecise: "ماشي محدد",
      description: "الوصف (إلا حبيت)",
      descriptionAjout: "الوصف (إلا حبيت)",
      prix: "السومة بالدينار",
      prixAjout: "السومة بالدينار *",
      publier: "انشر السلعة",
      enregistrer: "سجّل",
      enregistre: "السلعة تسجّلت.",
      enregistrementImpossible: "ما قدرناش نسجّلو السلعة. عاود جرّب.",
      proposeIA: "اقترحها الذكاء الاصطناعي",
      iaPrepare: "الذكاء الاصطناعي راهو يوجّد الفيشة…",
      brouillonRestaure: "رجّعنا المسودة",
      effacer: "امسح",
      brouillonPhotos: "التصاور ما يتحفظوش في المسودة. اختارهم من جديد.",
      taillesReinitialisees: "المقاسات رجعو من الأول لهاد النوع",
      couleur: "اللون (إلا حبيت)",
      contenances: "الأحجام اللي كاينين *",
      tailles: "المقاسات اللي كاينين *",
      unique: "واحد",
      tailleUnique: "مقاس واحد",
      categorieDabord: "اختار النوع الأول.",
      couleurs: {
        Noir: "كحل",
        Blanc: "بيض",
        Gris: "رمادي",
        Beige: "بيج",
        Marron: "قهوي",
        "Bleu marine": "زرق غامق",
        Bleu: "زرق",
        Vert: "خضر",
        Kaki: "كاكي",
        Rouge: "حمر",
        Bordeaux: "بوردو",
        Rose: "روز",
        Jaune: "صفر",
        Orange: "ليموني",
        Violet: "موف",
        Multicolore: "بزاف الألوان",
      },
    },
    photos: {
      legende: "تصاور السلعة",
      titre: "التصاور · من 1 حتى 5 *",
      photo: "صورة {n}",
      retirer: "نحّي الصورة {n}",
      galerie: "اختار من الغاليري",
      prendre: "صوّر",
      ajouter: "+ زيد تصاور",
    },
    descriptionArabe: {
      titre: "الوصف بالعربية",
      traduction: "راهي تترجم…",
      generer: "ترجم للعربية",
      texte: "النص بالعربية (إلا حبيت)",
      saisieChangee: "الكتابة نتاعك تبدّلت وقت الترجمة. خلّيناها كيما هي.",
    },
    nouvel: {
      titre: "سلعة جديدة",
      titreMajuscules: "سلعة جديدة",
      enLigne: "السلعة راهي في الموقع",
      copieImpossible: "النسخ الأوتوماتيك ما يخدمش. حدّد الرابط وانسخو.",
      autre: "زيد سلعة أخرى",
      profilImpossible: "ما قدرناش نحمّلو الحساب نتاعك. عاود جرّب من بعد شوية.",
    },
    modifier: {
      titre: "بدّل السلعة",
      suppression: "حذف السلعة",
      confirmer: "تحب تحذف هاد السلعة وتصاورها نهائيا؟",
      oui: "إيه، احذف السلعة",
      supprimer: "احذف السلعة",
      suppressionImpossible: "ما قدرناش نحذفو السلعة. عاود جرّب.",
      articleImpossible: "ما قدرناش نحمّلو هاد السلعة. عاود جرّب.",
    },
    promo: {
      titre: "التخفيض",
      prixNormal: "السومة العادية المسجّلة:",
      prixPromo: "سومة التخفيض بالدينار",
      pourcentage: "التخفيض بالمية",
      dateFin: "تاريخ النهاية",
      badge: "العلامة",
      parDefaut: "(العادي)",
      flash: "تخفيض فلاش",
      enregistrer: "سجّل التخفيض",
      arreter: "وقّف التخفيض",
      enregistree: "التخفيض تسجّل.",
      arretee: "التخفيض حبس.",
      impossible: "ما قدرناش نبدّلو التخفيض. عاود جرّب.",
      pourcentageInvalide: "اكتب نسبة كثر من 0 وأقل من 100.",
    },
    commandes: {
      titre: "الطلبات اللي جاوك",
      recherche: "الرقم ولا الاسم",
      effacerRecherche: "امسح البحث",
      scannerLibelle: "سكاني QR code تاع زبون",
      resultat: "{n} نتيجة لـ « {q} » · كل المراحل",
      resultats: "{n} نتائج لـ « {q} » · كل المراحل",
      etapesLibelle: "المراحل",
      impossible: "ما قدرناش نحمّلو الطلبات. عاود جرّب.",
      preparationUne: "ليستة التوجاد ({n} طلب)",
      preparationPlusieurs: "ليستة التوجاد ({n} طلبات)",
      remisePretes: "التسليم: سكاني QR code تاع الزبون (الزر « سكاني » الفوق)، ولا حل الطلب واختار « سلّمت بلا QR code ».",
      seules: "غير الـ {n} اللولين باينين: قلّب بالرقم ولا الاسم.",
      rienTrouve: "ما لقيت والو؟ اكتب رقم الطلب (مثلا 131) ولا بداية الاسم.",
      etapes: {
        a_confirmer: {
          libelle: "باش تأكّد",
          vide: "ما كاين حتى طلب باش تأكّدو.",
          heure: "وصلت",
        },
        a_preparer: {
          libelle: "باش توجّد",
          vide: "ما كاين حتى طلب باش توجّدو.",
          heure: "تأكّدت",
        },
        pretes: {
          libelle: "واجدين",
          vide: "ما كاين حتى طلب واجد.",
          heure: "واجدة",
        },
        terminees: {
          libelle: "كملو",
          vide: "ما كاين حتى طلب كمل في 7 أيام اللي فاتو.",
          heure: "كملت",
        },
      },
    },
    miseAJour: {
      aJour: "محدّث · {heure}",
      perdue: "الأنترنت راحت، راهو يعاود… · آخر تحديث على {heure}",
      actualiser: "حدّث",
      sonActive: "الصوت خدّام",
      couper: "قطع",
      activerSon: "شعّل الصوت",
      nouvelles: "{n} طلبات جداد · اللخرانية: رقم {numero}",
      nouvelle: "طلب جديد رقم {numero}",
    },
    tableau: {
      aucune: "ما كاين حتى طلب كيما هكا.",
      groupeImpossible: "ما قدرناش نبدّلو الطلبات. شوف الأنترنت ديالك.",
      ligneImpossible: "ما قدرناش نبدّلو الطلب. شوف الأنترنت ديالك.",
      confirmerLes: "أكّد الـ {n}",
      confirmerUne: "أكّد الطلب",
      marquerPrete: "حطّها واجدة ({n})",
      marquerPretes: "حطّهم واجدين ({n})",
      toutCocher: "علّم الكل ({n})",
      urgentes: "اللي مزروبين الفوق",
      colNumero: "رقم",
      colPrenom: "الاسم",
      colArticles: "السلع",
      colAEncaisser: "باش تقبض",
      colEtape: "المرحلة",
      colEcheance: "الوقت",
      colBon: "بون",
      cochee: "{n} طلب معلّم",
      cochees: "{n} طلبات معلّمين",
      decocher: "نحّي العلامات",
      auPlus: "{n} على الأكثر في خطرة",
      cocher: "علّم الطلب رقم {n}",
      numeroCourt: "رقم {n}",
      nouveau: "جديد",
      article: "{n} سلعة",
      articles: "{n} سلع",
      heureA: "{etape} على {heure}",
      bon: "بون {n}",
      corrigerStock: "صلّح السطوك في السلع نتاعي",
      hier: "البارح {heure}",
      heure: "{h}:{m}",
      moinsUneMinute: "أقل من دقيقة",
      minutes: "{m} دق",
      heures: "{h} سا",
      heuresMinutes: "{h} سا {m}",
      attend: "يستنّى من {duree}",
      confirmeeIlYa: "تأكّدت هادي {duree}",
      prete: "واجدة",
      expiree: "فات وقتها، تستنّى",
      expireDans: "يفوت وقتها في {duree}",
      aucuneModifiee: "حتى طلب ما تبدّل.",
      confirmees: "{n} طلب تأكّد.",
      confirmeesPlusieurs: "{n} طلبات تأكّدو.",
      pretesUne: "{n} طلب ولّا واجد.",
      pretesPlusieurs: "{n} طلبات ولّاو واجدين.",
      dejaConfirmee: "رقم {n}: راهو مأكّد من قبل.",
      dejaPrete: "رقم {n}: راهو واجد من قبل.",
      nonConfirmee: "رقم {n} ما تأكّدش: {message}",
      nonPrete: "رقم {n} ما ولّاش واجد: {message}",
    },
    carte: {
      aucune: "ما كاين حتى طلب هنا دابا.",
      choisirMotif: "اختار علاش راك تلغي.",
      signalerImpossible: "ما قدرناش نبلّغو على هاد الزبون. شوف الأنترنت ديالك.",
      commande: "الطلب رقم {n}",
      aRecuperer: "يتدّى حتى {date}",
      whatsapp: "واتساب",
      total: "المجموع",
      piece: "{n} حبة",
      pieces: "{n} حبات",
      aEncaisser: "باش تقبض",
      noteClient: "كلمة الزبون: « {note} »",
      motif: "السبب: {motif}",
      pasVenuSignale: "الزبون ما جاش · تبلّغ نهار {date}",
      annuleParBleDeal: " (BleDeal لغاه)",
      remiseScan: "التسليم: سكاني QR code تاع الزبون.",
      sansQrQuestion: "الزبون ما عندو لا QR code لا كود؟ سلّمو الطلب غير إلا عرفتو.",
      sansQrBon: "بلا QR code، البون ما يتحسبش: اقبض {montant}. البون يبقى للزبون.",
      confirmerRemise: "أكّد التسليم",
      remisSansQr: "سلّمت بلا QR code",
      motifAnnulation: "سبب الإلغاء",
      messageClient: "كلمة للزبون (إلا حبيت)",
      annulerCommande: "الغي الطلب",
      pasVenuQuestion: "الزبون ما جاش يدّي الطلب؟ يجيه تنبيه في الواتساب؛ في المرة الخامسة يتبلوكا الحساب نتاعو.",
      confirmerPasVenu: "أكّد: ما جاش",
      clientPasVenu: "الزبون ما جاش",
      actions: {
        confirmee: "أكّد",
        prete: "واجدة",
        recuperee: "تدّات",
      },
    },
    preparation: {
      titre: "ليستة التوجاد",
      retour: "→ الطلبات",
      confirmee: "{n} طلب مأكّد",
      confirmees: "{n} طلبات مأكّدين",
      piece: "{n} حبة",
      pieces: "{n} حبات",
      rien: "ما كاين والو باش توجّد دابا.",
      parCommande: "حسب الطلب",
      uneFois: "كي توجّدهم: علّمهم في « باش توجّد » ومن بعد « حطّهم واجدين ».",
      imprimer: "اطبع",
      dateLongue: "{jour} {date} على {heure}",
    },
    retrait: {
      titre: "التسليم",
      titrePage: "تسليم طلب",
      scannerAutre: "سكاني طلب آخر",
      voirCommandes: "شوف الطلبات",
      remise: "الطلب تسلّم",
      remiseTexte: "رقم {n} · {montant} · ولّا « تدّات ». السطوك كان محدّث من قبل.",
      bonRembourse: "{bon} تاع {montant}: BleDeal يخلّصهولك ({releve}).",
      trouvee: "لقينا الطلب · {mode}",
      parCode: "بالكود",
      parQr: "بالـ QR code",
      prete: "واجدة · حتى {date}",
      articles: "السلع",
      sousTotal: "المجموع قبل البون",
      bonBleDeal: "{bon} BleDeal",
      aEncaisser: "تقبض كاش",
      rembourses: "هادو {montant} يخلّصهملك BleDeal ({releve}).",
      parCodeBon: "بالكود، البون ما يتحسبش: اقبض {montant}. البون يبقى للزبون.",
      parCodeRemise: "التسليم بالكود: لا بون العرضة لا العرضة تاع BleDeal. سكاني خير QR code تاع الزبون.",
      verifier: "شوف السلع مع الزبون قبل ما تسلّم. واحد من عايلتو ولا صاحبو يقدر يجي في بلاصتو: عادي.",
      remis: "تسلّم للزبون",
      impossible: "ما قدرناش نسلّمو الطلب. شوف الأنترنت ديالك.",
      releve: "كشف {mois}",
      releveVoyelle: "كشف {mois}",
    },
    scanner: {
      titre: "سكاني QR code تاع الزبون",
      titrePage: "سكاني QR code تاع زبون",
      placez: "حط QR code تاع الزبون وسط الكادر.",
      camera: "الكاميرا",
      ouverture: "راهي تتحل الكاميرا…",
      navigateur: "في الواتساب ولا الإنستغرام، حل الفضاء نتاعك في Chrome ولا Safari.",
      reessayer: "عاود جرّب الكاميرا",
      lampe: "الضو",
      codeLibelle: "الكاميرا ما خدمتش؟ اكتب الكود تاع 6 أرقام",
      voir: "شوف الطلب",
      retourCommandes: "رجوع للطلبات",
      tapez: "اكتب الأرقام الستة تاع الكود.",
      lectureImpossible: "ما قدرناش نقراو هاد الطلب. شوف الأنترنت ديالك.",
    },
    avis: {
      titre: "الآراء",
      seuil: "النقطة تبان للزبائن من 3 آراء وفوق.",
      etoiles: "{n} نجوم من 5",
      votreReponse: "الرد نتاعك: {reponse}",
      masquee: "خبّاتها المراقبة: الزبائن ما بقاوش يشوفوها.",
      aucun: "مازال ما كاين حتى راي. الزبائن يقدرو يعطيو نقطة للحانوت نتاعك من بعد ما يدّيو بالـ QR code نتاعهم.",
      pasSupprimer: "ما تقدرش تحذف راي. راي كذاب ولا فيه سبّان: « بلّغ ».",
      impossible: "ما قدرناش نحمّلو الآراء نتاعك. عاود جرّب.",
      reponseVide: "اكتب الرد نتاعك.",
      reponseTrop: "الرد ما يفوتش {n} حرف.",
      publierImpossible: "ما قدرناش ننشرو الرد. عاود جرّب.",
      reponseLibelle: "الرد نتاعك قدام الناس (مرة وحدة برك)",
      publication: "راهو يتنشر…",
      publier: "انشر الرد",
    },
    statistiques: {
      titre: "الإحصائيات نتاعي",
      periode: "مدة الإحصائيات",
      jours: "{n} يوم",
      sur: "في {n} يوم اللي فاتو.",
      vuesVitrine: "شحال من واحد شاف الحانوت",
      vuesArticles: "شحال من مرة تشافو السلع",
      clics: "الضغطات على « احجز »",
      top: "الـ 5 سلع اللي تشافو كثر",
      vuesClics: "{vues} مشاهدة · {clics} ضغطة على « احجز »",
      aucune: "حتى سلعة ما تشافت في هاد المدة.",
      impossible: "ما قدرناش نحمّلو الإحصائيات نتاعك. عاود جرّب.",
      indisponible: "السلعة ما بقاتش",
    },
    position: {
      titre: "البلاصة في الخريطة",
      statuts: {
        en_attente: "الحانوت يستنّى",
        validee: "الحانوت مقبول",
        suspendue: "الحانوت موقّف",
      },
      ville: "المدينة: {ville}",
      regler: "صلّحها قبل ما يتقبل الحانوت: من بعد، غير BleDeal يقدر يبدّلها.",
      enregistrer: "سجّل البلاصة",
      carte: "خريطة بلاصة الحانوت",
      aucune: "الحانوت نتاعك مازال ما عندو حتى بلاصة في الخريطة.",
      impossible: "ما قدرناش نسجّلو البلاصة. عاود جرّب.",
      retiree: "البلاصة تنحّات.",
      enregistree: "البلاصة تسجّلت.",
      contacter: "باش تبدّل بلاصة الحانوت في الخريطة، اتصل بـ BleDeal.",
      recherche: "راهو يقلّب على البلاصة… (20 ثانية على الأكثر)",
      lue: "الإحداثيات اللي في الرابط: {position}. شوف الدبوس في الخريطة.",
      facultative: "إلا حبيت، بصح بلا بلاصة الحانوت ما يبانش في الخريطة.",
      jeSuis: "راني في الحانوت: خود البلاصة نتاعي",
      deplacez: "حرّك الدبوس بصبعك وحطّو على باب الحانوت.",
      touchez: "اضغط على الخريطة باش تحط الدبوس.",
      retirer: "نحّي البلاصة",
      collerLien: "حط رابط Google Maps",
      aideLien: "في Google Maps: Partager › Copier le lien، ومن بعد حلّو وانسخ العنوان كامل (فيه « @35,… »). BleDeal عمرو ما يحل الرابط.",
      ou: "ولا",
      lire: "اقرا",
      latitude: "خط العرض (Latitude)",
      longitude: "خط الطول (Longitude)",
      aLaMain: "اكتب الإحداثيات بيدك",
      trouvee: "لقينا البلاصة · الدقة ± {m} م",
      peuPrecise: "البلاصة ماشي دقيقة (± {m} م): شعّل الـ GPS، قرّب للباب، ولا حرّك الدبوس.",
    },
    partage: {
      titre: "شارك الحانوت نتاعي",
      texte: "حط هاد الرابط في البيو تاع Instagram ولا TikTok ولا Facebook، وابعثو في الواتساب.",
      copie: "الرابط تنسخ",
      copieImpossible: "ما قدرناش ننسخو: حدّد الرابط وانسخو.",
      whatsapp: "ابعث على واتساب",
      qr: "QR code تاع رابط {nom}",
      telecharger: "حمّل QR code",
      imprimer: "اطبع الأفيش",
      suspendue: "الحانوت نتاعك موقّف: الرابط يبيّن « الحانوت ما راهوش متوفر ».",
      attente: "الرابط نتاعك يخدم كي يقبل BleDeal الحانوت نتاعك.",
    },
    conditions: {
      titre: "شروط التجار",
      intro: "قبل ما تخدم بالفضاء نتاعك، اقرا واقبل شروط التجار (النسخة تاع {version}).",
      francais: "النص الرسمي تاع الشروط بالفرنسية (الرابط اللي تحت). هاد الملخص يعاونك باش تفهمو؛ الترجمة الكاملة تجي من بعد المراجعة القانونية.",
      provisoire: "نسخة مؤقتة، راهي في المراجعة القانونية.",
      resume1: "BleDeal ما يبيع والو وما يقبض والو: انت اللي تبيع باسمك وتقبض الدراهم كاش كي يجي الزبون يدّي الطلب.",
      resume2: "السلعة الأصلية برك: ما كاش التقليد ولا السلع الممنوعة (الشراب، الدخان، الدوا…).",
      resume3: "المعلومات تاع الزبائن (الاسم، اللقب، التيليفون) تخدم غير للطلب اللي راهو ماشي.",
      resume4: "البونات: تنقّصهم في الكاسة كي يتسلّم الطلب بالـ QR code؛ وBleDeal يخلّصهملك في الكشف تاع كل شهر. بلا QR code ما كاش تخليص.",
      resume5: "المراقبة: BleDeal يقدر يخبّي سلعة، ينبّهك ولا يوقّف الحانوت؛ وكل قرار يتسجّل.",
      lire: "اقرا شروط التجار",
      confidentialite: "سياسة الخصوصية",
      case: "قريت ونقبل شروط التجار (النسخة تاع {version}) وسياسة الخصوصية.",
      accepter: "نقبل",
      connexionPerdue: "الأنترنت راحت. عاود جرّب.",
    },
    bons: {
      titre: "البونات اللي نخلّصوهملك",
      ceMois: "هاد الشهر: {resume}",
      resume: "{bons} · {montant}",
      un: "{n} بون",
      plusieurs: "{n} بونات",
      parOrigine: "حسب المصدر",
      plafond: "الحد تاع {nom}: {compte} بون في الحانوت نتاعك.",
      paye: "{mois}: {montant} · تخلّص نهار {date}",
      payeReference: "{mois}: {montant} · تخلّص نهار {date}، المرجع {reference}",
      aPayer: "{mois}: {montant} · يتخلّص قبل {date}",
      enCours: "{mois}: {montant} · مازال الشهر ما كملش",
      detail: "التفاصيل تاع الطلبات",
      ligne: "رقم {numero} · {origine} · {date}",
      origineParrainage: "العرضة",
      origineBienvenue: "مرحبا",
      origineInscription: "التسجيل في الحانوت",
      origineCampagne: "حملة",
      origineAvis: "رأي",
      etatARembourser: "باش يتخلّص",
      etatDeCote: "محطوطة على جنب",
      etatRefuse: "مرفوضة",
      partBoutique: "بون مرحبا تاع زبون تسجّل عندك: تنقّص البون كامل في الكاسة، وBleDeal يخلّصلك البون ناقص الحصة نتاعك.",
      explication: "BleDeal يخلّصلك كل شهر البونات (العرضة، مرحبا، الحملات) اللي نقّصتهم في طلبات تسلّمت بالـ QR code (الكشف يتسكّر نهار 1، والخلاص قبل نهار 10). بالكود تاع 6 أرقام، البون ما يتحسبش.",
    },
    connexion: {
      titre: "ادخل",
      sousTitre: "فضاء التاجر نتاعك",
      lienInvalide: "هاد رابط الدخول ماشي صالح، فات وقتو ولا تخدم من قبل. اطلب رابط جديد.",
    },
  },
};
