// US-23 : textes français de l'interface (langue par défaut). Les mêmes clés existent en arabe (ar.ts).
// Les {noms} sont remplacés par remplir() de lib/langue.ts.

export const fr = {
  entete: {
    navigation: "Navigation du site",
    rechercher: "Rechercher",
    panier: "Panier",
    // US-24.3 : lien « Carte » ; le panier devient une icône de sac avec le nombre (nom lu par les lecteurs d’écran).
    carte: "Carte",
    panierUnArticle: "Panier, 1 article",
    panierArticles: "Panier, {n} articles",
    // US-29.2 : bouton « Oran ▾ » (à partir de 2 villes ouvertes).
    changerVille: "Changer de ville, ville actuelle : {ville}",
  },
  villes: {
    // US-29.2 : page /villes (textes 2 à 7 du module 16).
    metaTitre: "Choisir sa ville",
    titre: "Choisissez votre ville",
    texte: "Les promos et les boutiques dépendent de la ville. Vous pourrez en changer à tout moment.",
    localiser: "Me localiser",
    recherche: "Recherche de votre position…",
    confidentialite: "Votre position reste sur votre téléphone : elle n’est ni envoyée ni enregistrée.",
    proche: "Vous êtes près de {ville}.",
    horsVilles: "Pas encore de boutiques BleDeal près de vous : choisissez une ville ci-dessous.",
    introuvable: "Position introuvable : choisissez une ville ci-dessous.",
    inconnue: "Cette ville n’est pas encore sur BleDeal.",
    boutiqueUne: "{n} boutique",
    boutiques: "{n} boutiques",
    liste: "Villes",
    actuelle: "ville actuelle",
  },
  langue: {
    groupe: "Langue",
    // Le bouton montre l'autre langue, écrite dans sa propre langue.
    autre: "عربي",
    autreNom: "العربية",
    autreCode: "ar",
  },
  erreur: {
    titre: "Une erreur est survenue",
    reessayer: "Réessayer",
  },
  introuvable: {
    titre: "Page introuvable",
    retour: "Retour à l’accueil",
  },
  listes: {
    univers: { femme: "Femme", homme: "Homme", enfant: "Enfant", beaute: "Beauté" },
    genres: { homme: "Homme", femme: "Femme", enfant: "Enfant", mixte: "Mixte" },
    genresBeaute: { femme: "Pour elle", homme: "Pour lui", mixte: "Mixte" },
    raccourcisBeaute: { "Parfums": "Parfums", "Maquillage": "Maquillage", "Soins visage et corps": "Soins", "Cheveux": "Cheveux", "Hammam et traditionnel": "Hammam" },
    groupesCategories: { mode: "Mode", beaute: "Beauté" },
    categories: {
      "T-shirts et polos": "T-shirts et polos",
      "Chemises": "Chemises",
      "Pulls et sweats": "Pulls et sweats",
      "Vestes et manteaux": "Vestes et manteaux",
      "Pantalons et jeans": "Pantalons et jeans",
      "Survêtements et ensembles": "Survêtements et ensembles",
      "Robes": "Robes",
      "Jupes": "Jupes",
      "Abayas, djellabas, kamis": "Abayas, djellabas, kamis",
      "Tenues traditionnelles": "Tenues traditionnelles",
      "Hijabs et foulards": "Hijabs et foulards",
      "Chaussures": "Chaussures",
      "Sacs": "Sacs",
      "Accessoires": "Accessoires",
      "Parfums": "Parfums",
      "Maquillage": "Maquillage",
      "Soins visage et corps": "Soins visage et corps",
      "Cheveux": "Cheveux",
      "Hammam et traditionnel": "Hammam et traditionnel",
    },
    tailleUnique: "Unique",
  },
  accueil: {
    univers: "Univers",
    titre: "Les promos {deVille}", // US-29.3 : « Les promos d’Oran », « Les promos de Tlemcen »
    sousTitre: "Réservez sur WhatsApp · Payez en boutique",
    voirPromos: "Voir les promos",
    creditPhoto: "Photo :",
    lesUnivers: "Les univers",
    piecesPhares: "Pièces phares",
    enCeMoment: "En ce moment",
    toutVoir: "Tout voir",
    espaceCommercant: "Espace commerçant",
  },
  promos: {
    aucune: "Aucune promo en cours. Revenez bientôt découvrir les nouveautés.",
    chargement: "Chargement…",
    erreurSuite: "Impossible de charger la suite. Réessayez.",
    reessayer: "Réessayer",
    voirPlus: "Voir plus de promos",
  },
  carte: {
    aucunePhoto: "Aucune photo",
    reduction: "−{n} %",
  },
  catalogue: {
    titre: "Le catalogue",
    rechercherArticle: "Rechercher un article",
    exemple: "Polo, jean, robe, parfum…",
    filtres: "Filtres",
    univers: "Univers",
    categorie: "Catégorie",
    toutes: "Toutes",
    tous: "Tous",
    taille: "Taille",
    genre: "Genre",
    quartier: "Quartier",
    prixMin: "Prix minimum (DA)",
    prixMax: "Prix maximum (DA)",
    enPromo: "En promo seulement",
    rechercher: "Rechercher",
    effacer: "Effacer les filtres",
    unResultat: "{n} résultat",
    resultats: "{n} résultats",
    aucun: "Aucun article ne correspond à votre recherche. Essayez d’autres critères ou effacez les filtres.",
    aucunBeaute: "Aucun produit de beauté pour le moment.",
    aucunVille: "Pas encore d’articles à {ville}.", // US-29.3 (texte 11)
    contenance: "Contenance",
    pour: "Pour",
    tout: "Tout",
    categoriesBeaute: "Catégories beauté",
    pagination: "Pagination du catalogue",
    precedent: "Précédent",
    suivant: "Suivant",
  },
  fiche: {
    retour: "Retour",
    aucunePhoto: "Aucune photo",
    jusquAu: "jusqu’au {date}",
    plusDisponible: "Article plus disponible",
    vendu: "Cet article a été vendu",
    autresArticles: "Autres articles de la boutique",
    aucunAutre: "Aucun autre article disponible",
    photosDe: "Photos de {titre}",
    galerie: "Galerie défilable",
    photoN: "{titre} — photo {n} sur {total}",
    photoPrecedente: "Photo précédente",
    photoSuivante: "Photo suivante",
    voirPhoto: "Voir la photo {n}",
    photoSur: "Photo {n} sur {total}",
    partager: "Partager",
    lienCopie: "Lien copié",
    partageImpossible: "Impossible de partager le lien.",
    taille: "Taille",
    tailleN: "Taille {taille}",
    tailleEpuisee: "Taille {taille}, épuisée",
    choisirTaille: "Choisissez une taille pour commander.",
    aucuneTaille: "Aucune taille disponible.",
    contenance: "Contenance",
    contenanceN: "Contenance {taille}",
    contenanceEpuisee: "{taille}, épuisée",
    choisirContenance: "Choisissez une contenance pour commander.",
    aucuneContenance: "Aucune contenance disponible.",
    quantite: "Quantité",
    quantiteN: "Quantité : {n}",
    moins: "Une pièce de moins",
    plus: "Une pièce de plus",
    ajouter: "Ajouter au panier",
    ajoute: "Ajouté au panier.",
    voirPanier: "Voir le panier",
    viderEtAjouter: "Vider le panier et ajouter",
    ajoutImpossible: "Impossible d’ajouter l’article au panier.",
    confirmation: "La boutique confirme votre commande. Paiement en boutique.",
    question: "Une question ? WhatsApp",
  },
  signaler: {
    bouton: "Signaler cet article",
    motif: "Motif du signalement",
    choisir: "Choisir un motif",
    contrefacon: "Contrefaçon",
    contenuInapproprie: "Contenu inapproprié",
    arnaque: "Arnaque",
    autre: "Autre",
    commentaire: "Commentaire (facultatif)",
    envoi: "Envoi…",
    envoyer: "Envoyer le signalement",
    choisirMotif: "Choisissez un motif.",
    echec: "Le signalement n’a pas pu être envoyé. Réessayez.",
  },
  vitrine: {
    partager: "Partager la boutique",
    adresseInconnue: "Adresse non renseignée",
    horairesInconnus: "Horaires non renseignés",
    whatsapp: "WhatsApp",
    itineraire: "Itinéraire",
    localisation: "Localisation de la boutique",
    carte: "Carte : {nom}",
    itineraireVers: "Itinéraire vers {nom}",
    articles: "Articles disponibles · promos en premier",
    aucun: "Aucun article disponible pour le moment.",
    indisponible: "Boutique indisponible",
    retour: "Retour à l’accueil",
  },
  // US-31.2 : suivre une boutique (bouton de la vitrine, « Mes boutiques » dans /compte).
  suivre: {
    suivre: "Suivre",
    suivie: "✓ Suivie",
    enCours: "Un instant…",
    confirmer: "Ne plus suivre {nom} ?",
    nePlusSuivre: "Ne plus suivre",
    garder: "Garder",
    mesBoutiques: "Mes boutiques ({n})",
    titre: "Mes boutiques",
    vide: "Vous ne suivez aucune boutique. Touchez « Suivre » sur la page d’une boutique pour la retrouver ici.",
    voirCarte: "Trouver des boutiques",
    promos: "{n} promos en cours",
    unePromo: "1 promo en cours",
    aucunePromo: "Pas de promo en cours",
    connexion: "Connectez-vous pour suivre une boutique.",
    plafond: "Vous suivez déjà 200 boutiques : arrêtez d’en suivre une pour en ajouter une autre.",
    introuvable: "Cette boutique n’est plus disponible.",
    reserve: "Seuls les comptes clients peuvent suivre une boutique.",
    erreur: "Action impossible pour le moment. Réessayez.",
    // US-31.3 : bandeau de la vitrine après le QR code de l'affiche.
    bienvenueTitre: "Bienvenue chez {nom}",
    bienvenueTexte: "Créez votre compte BleDeal : vous suivez la boutique et vous réservez ses articles en ligne, à payer en boutique.",
    creerCompte: "Créer mon compte",
  },
  panier: {
    titre: "Mon panier",
    vide: "Votre panier est vide.",
    voirArticles: "Voir les articles",
    articles: "Articles du panier",
    photo: "Photo",
    tailleEtPrix: "Taille {taille} · {prix}",
    contenanceEtPrix: "{taille} · {prix}",
    moins: "{titre} {taille} : une pièce de moins",
    plus: "{titre} {taille} : une pièce de plus",
    retirer: "Retirer {titre} ({taille})",
    note: "Note pour la boutique (facultative)",
    noteTropLongue: "La note doit faire {max} caractères au plus.",
    total: "Total",
    seConnecter: "Se connecter pour commander",
    verifierTitre: "Vérifiez votre numéro pour commander",
    verifierTexte: "Vous recevez un code à 6 chiffres sur WhatsApp. La boutique vous contactera sur ce numéro.",
    profilNom: "Avant votre première commande, indiquez votre nom.",
    profilNomTelephone: "Avant votre première commande, indiquez votre nom et votre numéro WhatsApp.",
    enregistrerContinuer: "Enregistrer et continuer",
    envoi: "Envoi en cours…",
    commander: "Commander",
    envoiImpossible: "Impossible d’envoyer la commande. Réessayez.",
    connexionPerdue: "Impossible d’envoyer la commande. Vérifiez votre connexion et réessayez.",
    mention: "La boutique confirme votre commande · Paiement en boutique · Un seul panier par boutique",
  },
  compte: {
    navigation: "Mon compte",
    monCompte: "Mon compte",
    monProfil: "Mon profil",
    mesCommandes: "Mes commandes",
    panier: "Panier",
    seDeconnecter: "Se déconnecter",
    monEspace: "Mon espace boutique",
    chargementImpossible: "Impossible de charger votre profil. Réessayez.",
    deconnexionImpossible: "Impossible de vous déconnecter. Réessayez.",
  },
  profil: {
    nom: "Nom et prénom",
    telephone: "Téléphone WhatsApp",
    contact: "La boutique vous contacte sur ce numéro pour votre commande.",
    enregistrer: "Enregistrer",
    enregistrement: "Enregistrement…",
  },
  numero: {
    verifie: "Téléphone vérifié",
    changer: "Changer de numéro",
    verifierTitre: "Vérifiez votre numéro pour commander",
    verifierTexte: "Nous vous envoyons un code à 6 chiffres sur WhatsApp. La boutique vous contactera sur ce numéro.",
  },
  connexion: {
    titre: "Se connecter",
    sousTitre: "Pour commander et suivre vos commandes",
    lienInvalide: "Ce lien de connexion est invalide, expiré ou déjà utilisé. Demandez un nouveau lien.",
    avecEmail: "Se connecter avec un e-mail (compte déjà créé par e-mail)",
    avecNumero: "Se connecter avec mon numéro de téléphone",
    email: "Adresse e-mail",
    emailAide: "Recevez un lien pour vous connecter sans mot de passe.",
    emailRecevoir: "Recevoir mon lien de connexion",
    envoi: "Envoi en cours…",
    emailInvalide: "Saisissez une adresse e-mail valide.",
    antiRobot: "Cochez d’abord le contrôle anti-robot.",
    emailEnvoye: "Un lien de connexion vous a été envoyé par e-mail",
    emailImpossible: "Impossible d’envoyer le lien de connexion. Réessayez dans quelques instants.",
  },
  code: {
    numero: "Numéro de mobile",
    aide: "Mobile algérien uniquement (05, 06 ou 07). Vous recevez un code à 6 chiffres sur WhatsApp.",
    recevoir: "Recevoir le code sur WhatsApp",
    envoi: "Envoi en cours…",
    antiRobot: "Cochez d’abord le contrôle anti-robot ci-dessous.",
    envoiImpossible: "Impossible d’envoyer le code. Vérifiez votre connexion et réessayez.",
    envoye: "Code envoyé au {numero}.",
    code: "Code à 6 chiffres",
    valider: "Valider le code",
    verification: "Vérification…",
    changer: "Changer de numéro ou recevoir un nouveau code",
    saisir: "Saisissez les 6 chiffres du code reçu.",
    verificationImpossible: "Impossible de vérifier le code. Vérifiez votre connexion et réessayez.",
  },
  commandes: {
    titre: "Mes commandes",
    aucune: "Vous n’avez pas encore de commande.",
    voirArticles: "Voir les articles",
    chargementImpossible: "Impossible de charger vos commandes. Réessayez.",
    commandeImpossible: "Impossible de charger la commande. Réessayez.",
    numero: "Commande n° {n}",
    statuts: { demandee: "Demandée", confirmee: "Confirmée", prete: "Prête", recuperee: "Récupérée", annulee: "Annulée", expiree: "Expirée" },
    titresSuivi: { demandee: "Commande envoyée", confirmee: "Confirmée par la boutique", prete: "Prête à récupérer", recuperee: "Récupérée", annulee: "Annulée", expiree: "Expirée" },
    motifs: { plus_en_stock: "Plus en stock", boutique_indisponible: "Boutique indisponible", client_a_annule: "Annulée par le client", autre: "Autre" },
    suivi: "Suivi de la commande",
    aVenir: " (à venir)",
    aRecuperer: "À récupérer avant le",
    motif: "Motif : {motif}",
    expiree: "Commande non récupérée dans les 24 heures : elle compte comme un no-show.",
    articles: "Articles commandés",
    total: "Total",
    note: "Votre note : « {note} »",
    ecrire: "Écrire à la boutique sur WhatsApp",
    voirBoutique: "Voir la boutique",
    mention: "Paiement en boutique · Annulation possible tant que la commande n’est pas prête",
    annuler: "Annuler ma commande",
    motAnnulation: "Un mot pour la boutique (facultatif)",
    confirmerAnnulation: "Confirmer l’annulation",
    retour: "Retour",
  },
  retrait: {
    // US-26.2 : QR code de retrait (client et proche). Textes 1 à 10 de la story US-26.
    bloc: "Mon QR code de retrait",
    consigne: "Montrez ce QR code au vendeur, dans la boutique. Vous payez sur place, en espèces.",
    sansCamera: "Pas de caméra ? Donnez ce code à 6 chiffres :",
    aPayer: "À payer en espèces",
    luminosite: "Montez la luminosité de l’écran pour que le QR code se lise bien.",
    envoyerProche: "Envoyer à un proche (WhatsApp)",
    copier: "Copier le lien",
    copie: "Lien copié.",
    copieImpossible: "Copie impossible : partagez le lien par WhatsApp.",
    avertissement: "Toute personne qui a ce lien peut récupérer la commande : ne l’envoyez qu’à quelqu’un de confiance.",
    altQr: "QR code de retrait de la commande n° {n}",
    code: "Code de retrait",
    metaTitre: "Commande à récupérer",
    titreProche: "Commande n° {n} à récupérer chez {boutique}",
    avant: "Avant le {date}",
    consigneProche: "Montrez ce QR code au vendeur, ou donnez-lui le code à 6 chiffres :",
    voirBoutique: "Voir la boutique",
    articles: "Articles à récupérer",
    recuperee: "Cette commande a déjà été récupérée.",
    annulee: "Cette commande a été annulée : il n’y a rien à récupérer.",
    expiree: "Cette commande a expiré : elle n’est plus à récupérer.",
    invalide: "Ce lien n’est pas valide.",
    impossible: "Impossible de charger la commande. Réessayez.",
  },
  noShows: {
    titre: "Commandes non récupérées ({n})",
    explication: "La boutique a signalé que vous n’êtes pas venu(e). Si c’est une erreur, contestez dans les {jours} jours : la commande ne compte plus tant que BleDeal n’a pas décidé (un compte déjà bloqué le reste jusqu’à cette décision). Une seule contestation à la fois.",
    enExamen: "Contestation en cours d’examen",
    refusee: "Contestation refusée : la commande compte",
    votreMotif: "Votre motif : {motif}",
    delaiDepasse: "Délai de contestation dépassé ({jours} jours).",
    attendre: "Vous pourrez contester celle-ci quand BleDeal aura répondu à votre contestation en cours.",
    contester: "Contester",
    pourquoi: "Pourquoi contestez-vous ?",
    envoi: "Envoi…",
    envoyer: "Envoyer la contestation",
    fermer: "Fermer",
  },
  carteBoutiques: {
    // US-24.3 : page /carte et bloc de l'accueil.
    metaTitre: "Carte des boutiques",
    titre: "Les boutiques sur la carte",
    nombreUn: "{n} boutique à {ville}",
    nombre: "{n} boutiques à {ville}",
    filtre: "Filtrer par univers",
    tous: "Tous",
    univers: { femme: "Femme", homme: "Homme", enfant: "Enfant", beaute: "Beauté" },
    autourDeMoi: "Autour de moi",
    autourActif: "Autour de moi · actif",
    recherche: "Recherche de votre position…",
    confidentialite: "Votre position reste sur votre téléphone : elle n’est ni envoyée ni enregistrée.",
    refus: "Localisation refusée : la liste reste triée par nom. Vous pouvez l’autoriser dans les réglages du navigateur.",
    introuvable: "Position introuvable pour le moment. Réessayez dehors ou près d’une fenêtre.",
    reessayer: "Réessayer",
    region: "Carte des boutiques {deVille}",
    vous: "Vous",
    indisponible: "La carte ne peut pas s’afficher. La liste des boutiques reste ci-dessous.",
    promosUne: "{n} promo en cours",
    promos: "{n} promos en cours",
    aucunePromo: "Aucune promo en cours",
    distance: "à {d}",
    voirBoutique: "Voir la boutique",
    itineraire: "Itinéraire",
    fermer: "Fermer",
    listeParNom: "Les boutiques · par nom",
    listeProches: "Les boutiques · les plus proches d’abord",
    sansPosition: "Sans position sur la carte ({n})",
    aucuneUnivers: "Aucune boutique de cet univers pour le moment.",
    voirToutes: "Voir toutes les boutiques",
    aucune: "Aucune boutique sur la carte pour le moment.",
    erreur: "Impossible de charger les boutiques. Réessayez.",
    accueilTitre: "Les boutiques sur la carte",
    accueilTexte: "Trouvez les promos près de chez vous.",
    accueilLien: "Voir la carte",
  },
  parrainage: {
    // US-27 : parrainage (tutoiement, décision 9 du 9/10). Numéros = textes de la story US-27 (module 14).
    metaTitre: "Parrainage",
    etiquette: "Parrainage",
    titre: "Parraine tes amis", // 1
    intro: "Fais découvrir les promos des boutiques de ta ville. Quand ton ami récupère sa première commande en boutique, vous recevez chacun un bon de 300 DA.",
    commentCaMarche: "Comment ça marche",
    etape1: "Partage ton lien sur WhatsApp.", // 2
    etape2: "Ton ami s’inscrit avec son numéro et te choisit comme parrain.", // 3
    etape3: "Quand il récupère sa première commande en boutique, vous gagnez tous les deux.", // 4
    recompense: "Un bon de 300 DA chacun, à déduire en boutique.", // 5
    tonCode: "Ton code",
    partagerWhatsApp: "Partager sur WhatsApp", // 6
    copierLien: "Copier le lien", // 7
    lienCopie: "Lien copié.",
    copieImpossible: "Copie impossible : partage le lien par WhatsApp.",
    qrAlt: "QR code de ton lien de parrainage",
    qrTexte: "Ton ami peut scanner ce QR code avec son téléphone. Le lien ne montre ni ton nom ni ton numéro.",
    connecteToi: "Connecte-toi pour avoir ton lien",
    seConnecter: "Se connecter",
    reserveClients: "Le parrainage est réservé aux clients avec un numéro WhatsApp vérifié par code.",
    ferme: "Le parrainage n’est pas encore ouvert. Reviens bientôt !",
    bonTitre: "Ton bon de 300 DA",
    bonTexte: "Au panier, coche « Utiliser mon bon » : tu paies 300 DA de moins en boutique. C’est BleDeal qui paie ces 300 DA à la boutique.",
    voirMesBons: "Voir mes bons et mes filleuls",
    reglesTitre: "Les règles",
    regle1: "Parrain et filleul ont un numéro vérifié par code WhatsApp.",
    regle2: "Pas de parrainage de soi-même. Un seul parrain par compte.",
    regle3: "Le filleul choisit son parrain dans les 7 jours, avant sa première commande.",
    regle4: "Les bons arrivent après sa première commande d’au moins 2 000 DA, récupérée avec son QR code, pas à l’inscription.",
    regle5: "Bon valable 60 jours, un par commande, dès 1 000 DA d’achat.",
    regle6: "5 amis récompensés par mois au plus.",
    regle7: "BleDeal n’écrit jamais à tes amis : c’est toi qui partages.",
    invite: "Un ami t’invite sur BleDeal", // 12
    inviteConnexion: "Connecte-toi avec ton numéro WhatsApp, puis valide le code de ton ami.",
    // Saisie du parrain (US-27.2)
    tonParrain: "Ton parrain",
    champ: "Ton parrain (facultatif) : son numéro WhatsApp ou son code", // 8
    rappel: "Ton bon et celui de ton parrain arrivent après ta première commande d’au moins 2 000 DA, récupérée en boutique avec ton QR code.", // 24
    valider: "Valider",
    envoi: "Envoi…",
    enregistre: "C’est noté. Si ce numéro est celui d’un client BleDeal, il deviendra ton parrain après ton premier retrait en boutique.", // 9
    impossible: "Impossible d’enregistrer ton parrain. Réessaie.",
    parrainEnregistre: "Parrain enregistré",
    modifier: "Modifier",
    modificationsRestantes: "Tu peux encore le modifier {n} fois, avant ta première commande.",
    // Compte (US-27.3)
    monParrainage: "Mon parrainage",
    valides: "amis ont fait leur premier retrait", // 11 (le nombre est affiché à côté)
    valideUn: "ami a fait son premier retrait",
    enAttente: "en attente de leur premier retrait", // 11
    filleul: "{prenom} · {date}",
    bonFilleul: "bon de 300 DA",
    bonEnFile: "bon en attente (budget)",
    plafond: "Plafond du mois atteint : 5 amis récompensés. Les suivants reçoivent leur bon, pas toi, jusqu’à la fin du mois.",
    discretion: "Les amis en attente ne sont pas nommés. Aucun numéro n’est affiché.",
    aucunFilleul: "Aucun ami récompensé pour le moment : partage ton lien.",
    commentMarche: "Comment marche le parrainage ?",
    mesBons: "Mes bons", // 15
    nomBon: "Bon parrainage",
    disponible: "Disponible · valable jusqu’au {date}", // 16
    reserve: "Réservé pour la commande n° {n}", // 21
    utilise: "Utilisé le {date} chez {boutique}", // 22
    expire: "Expiré le {date}", // 23
    enFile: "Ton bon arrive le {date} (budget du mois atteint).", // 20
    annule: "Annulé",
    aideBons: "À utiliser au panier : 300 DA de moins, payés par BleDeal à la boutique.",
    // Accueil et suivi (US-27.3)
    accueilTitre: "Parraine tes amis", // 13
    accueilTexte: "300 DA chacun", // 13
    accueilLien: "Voir",
    merciTitre: "Merci !", // 14
    merciTexte: "Fais découvrir BleDeal à un ami : 300 DA chacun après sa première commande.", // 14
    partagerMonLien: "Partager mon lien",
    // Panier et suivi (US-27.4)
    utiliserBon: "Utiliser mon bon parrainage (−300 DA)", // 17
    ligneBon: "Bon parrainage",
    aPayerBoutique: "À payer en boutique", // 18
    sousMinimum: "Ton bon s’utilise dès 1 000 DA d’achat.", // 19
    noteBon: "Un bon par commande. Si la commande est annulée ou expire, le bon revient.",
    bonNonApplique: {
      aucun_bon: "Bon non appliqué : il a expiré ou n’est plus disponible. Ta commande reste au prix plein ; tu peux l’annuler si tu le souhaites.",
      minimum: "Bon non appliqué : il s’utilise dès 1 000 DA d’achat. Ta commande reste au prix plein.",
      boutique_exclue: "Bon non appliqué : cette boutique n’accepte pas les bons pour le moment. Ta commande reste au prix plein ; tu peux l’annuler si tu le souhaites.",
      erreur: "Bon non appliqué. Ta commande reste au prix plein ; tu peux l’annuler si tu le souhaites.",
    },
  },
  juridique: {
    // US-34.1 : pied de page et pages juridiques (textes provisoires, décision du propriétaire du 10/10).
    piedDePage: "Informations juridiques",
    conditions: "Conditions",
    commercants: "Commerçants",
    confidentialite: "Confidentialité",
    titres: {
      conditions: "Conditions d’utilisation",
      conditions_commercants: "Conditions commerçants",
      confidentialite: "Politique de confidentialité",
    },
    version: "Version du {date}",
    provisoire: "Version provisoire, en cours de relecture juridique.",
    traductionAttente: "La traduction arabe de ce texte arrive bientôt. Le texte ci-dessous est la version française.",
    // US-34.2 : acceptation par le client (textes n° 2 à 5 de la conception, docs/user-stories.md).
    caseInscription: "J’accepte les conditions d’utilisation et la politique de confidentialité, y compris l’utilisation de prestataires situés hors d’Algérie (Supabase, Vercel, WhatsApp…).",
    caseRequise: "Cochez la case pour créer votre compte.",
    conditionsChangees: "Nos conditions ont changé le {date}",
    accepterCommander: "Accepter et commander",
  },
};

export type Textes = typeof fr;
