// US-23 : textes français de l'interface (langue par défaut). Les mêmes clés existent en arabe (ar.ts).
// Les {noms} sont remplacés par remplir() de lib/langue.ts.

export const fr = {
  entete: {
    navigation: "Navigation du site",
    rechercher: "Rechercher",
    panier: "Panier",
    panierAvecNombre: "Panier ({n})",
  },
  langue: {
    groupe: "Langue",
    // Le bouton montre l'autre langue, écrite dans sa propre langue.
    autre: "عربي",
    autreNom: "العربية",
    autreCode: "ar",
  },
  erreur: {
    titre: "Une erreur est survenue",
    reessayer: "Réessayer",
  },
  introuvable: {
    titre: "Page introuvable",
    retour: "Retour à l’accueil",
  },
  listes: {
    univers: { femme: "Femme", homme: "Homme", enfant: "Enfant", beaute: "Beauté" },
    genres: { homme: "Homme", femme: "Femme", enfant: "Enfant", mixte: "Mixte" },
    groupesCategories: { mode: "Mode", beaute: "Beauté" },
    categories: {
      "T-shirts et polos": "T-shirts et polos",
      "Chemises": "Chemises",
      "Pulls et sweats": "Pulls et sweats",
      "Vestes et manteaux": "Vestes et manteaux",
      "Pantalons et jeans": "Pantalons et jeans",
      "Survêtements et ensembles": "Survêtements et ensembles",
      "Robes": "Robes",
      "Jupes": "Jupes",
      "Abayas, djellabas, kamis": "Abayas, djellabas, kamis",
      "Tenues traditionnelles": "Tenues traditionnelles",
      "Hijabs et foulards": "Hijabs et foulards",
      "Chaussures": "Chaussures",
      "Sacs": "Sacs",
      "Accessoires": "Accessoires",
      "Parfums": "Parfums",
      "Maquillage": "Maquillage",
      "Soins visage et corps": "Soins visage et corps",
      "Cheveux": "Cheveux",
      "Hammam et traditionnel": "Hammam et traditionnel",
    },
    tailleUnique: "Unique",
  },
  accueil: {
    univers: "Univers",
    titre: "Les promos d’Oran",
    sousTitre: "Réservez sur WhatsApp · Payez en boutique",
    voirPromos: "Voir les promos",
    creditPhoto: "Photo :",
    lesUnivers: "Les univers",
    piecesPhares: "Pièces phares",
    enCeMoment: "En ce moment",
    toutVoir: "Tout voir",
    espaceCommercant: "Espace commerçant",
  },
  promos: {
    aucune: "Aucune promo en cours. Revenez bientôt découvrir les nouveautés.",
    chargement: "Chargement…",
    erreurSuite: "Impossible de charger la suite. Réessayez.",
    reessayer: "Réessayer",
    voirPlus: "Voir plus de promos",
  },
  carte: {
    aucunePhoto: "Aucune photo",
    reduction: "−{n} %",
  },
  catalogue: {
    titre: "Le catalogue",
    rechercherArticle: "Rechercher un article",
    exemple: "Polo, jean, robe, parfum…",
    filtres: "Filtres",
    univers: "Univers",
    categorie: "Catégorie",
    toutes: "Toutes",
    tous: "Tous",
    taille: "Taille",
    genre: "Genre",
    quartier: "Quartier",
    prixMin: "Prix minimum (DA)",
    prixMax: "Prix maximum (DA)",
    enPromo: "En promo seulement",
    rechercher: "Rechercher",
    effacer: "Effacer les filtres",
    unResultat: "{n} résultat",
    resultats: "{n} résultats",
    aucun: "Aucun article ne correspond à votre recherche. Essayez d’autres critères ou effacez les filtres.",
    pagination: "Pagination du catalogue",
    precedent: "Précédent",
    suivant: "Suivant",
  },
  fiche: {
    retour: "Retour",
    aucunePhoto: "Aucune photo",
    jusquAu: "jusqu’au {date}",
    plusDisponible: "Article plus disponible",
    vendu: "Cet article a été vendu",
    autresArticles: "Autres articles de la boutique",
    aucunAutre: "Aucun autre article disponible",
    photosDe: "Photos de {titre}",
    galerie: "Galerie défilable",
    photoN: "{titre} — photo {n} sur {total}",
    photoPrecedente: "Photo précédente",
    photoSuivante: "Photo suivante",
    voirPhoto: "Voir la photo {n}",
    photoSur: "Photo {n} sur {total}",
    partager: "Partager",
    lienCopie: "Lien copié",
    partageImpossible: "Impossible de partager le lien.",
    taille: "Taille",
    tailleN: "Taille {taille}",
    tailleEpuisee: "Taille {taille}, épuisée",
    choisirTaille: "Choisissez une taille pour commander.",
    aucuneTaille: "Aucune taille disponible.",
    quantite: "Quantité",
    quantiteN: "Quantité : {n}",
    moins: "Une pièce de moins",
    plus: "Une pièce de plus",
    ajouter: "Ajouter au panier",
    ajoute: "Ajouté au panier.",
    voirPanier: "Voir le panier",
    viderEtAjouter: "Vider le panier et ajouter",
    ajoutImpossible: "Impossible d’ajouter l’article au panier.",
    confirmation: "La boutique confirme votre commande. Paiement en boutique.",
    question: "Une question ? WhatsApp",
  },
  signaler: {
    bouton: "Signaler cet article",
    motif: "Motif du signalement",
    choisir: "Choisir un motif",
    contrefacon: "Contrefaçon",
    contenuInapproprie: "Contenu inapproprié",
    arnaque: "Arnaque",
    autre: "Autre",
    commentaire: "Commentaire (facultatif)",
    envoi: "Envoi…",
    envoyer: "Envoyer le signalement",
    choisirMotif: "Choisissez un motif.",
    echec: "Le signalement n’a pas pu être envoyé. Réessayez.",
  },
  vitrine: {
    partager: "Partager la boutique",
    adresseInconnue: "Adresse non renseignée",
    horairesInconnus: "Horaires non renseignés",
    whatsapp: "WhatsApp",
    itineraire: "Itinéraire",
    localisation: "Localisation de la boutique",
    carte: "Carte : {nom}",
    itineraireVers: "Itinéraire vers {nom}",
    articles: "Articles disponibles · promos en premier",
    aucun: "Aucun article disponible pour le moment.",
    indisponible: "Boutique indisponible",
    retour: "Retour à l’accueil",
  },
  panier: {
    titre: "Mon panier",
    vide: "Votre panier est vide.",
    voirArticles: "Voir les articles",
    articles: "Articles du panier",
    photo: "Photo",
    tailleEtPrix: "Taille {taille} · {prix}",
    moins: "{titre} {taille} : une pièce de moins",
    plus: "{titre} {taille} : une pièce de plus",
    retirer: "Retirer {titre} ({taille})",
    note: "Note pour la boutique (facultative)",
    noteTropLongue: "La note doit faire {max} caractères au plus.",
    total: "Total",
    seConnecter: "Se connecter pour commander",
    verifierTitre: "Vérifiez votre numéro pour commander",
    verifierTexte: "Vous recevez un code à 6 chiffres sur WhatsApp. La boutique vous contactera sur ce numéro.",
    profilNom: "Avant votre première commande, indiquez votre nom.",
    profilNomTelephone: "Avant votre première commande, indiquez votre nom et votre numéro WhatsApp.",
    enregistrerContinuer: "Enregistrer et continuer",
    envoi: "Envoi en cours…",
    commander: "Commander",
    envoiImpossible: "Impossible d’envoyer la commande. Réessayez.",
    connexionPerdue: "Impossible d’envoyer la commande. Vérifiez votre connexion et réessayez.",
    mention: "La boutique confirme votre commande · Paiement en boutique · Un seul panier par boutique",
  },
  compte: {
    navigation: "Mon compte",
    monCompte: "Mon compte",
    monProfil: "Mon profil",
    mesCommandes: "Mes commandes",
    panier: "Panier",
    seDeconnecter: "Se déconnecter",
    monEspace: "Mon espace boutique",
    chargementImpossible: "Impossible de charger votre profil. Réessayez.",
    deconnexionImpossible: "Impossible de vous déconnecter. Réessayez.",
  },
  profil: {
    nom: "Nom et prénom",
    telephone: "Téléphone WhatsApp",
    contact: "La boutique vous contacte sur ce numéro pour votre commande.",
    enregistrer: "Enregistrer",
    enregistrement: "Enregistrement…",
  },
  numero: {
    verifie: "Téléphone vérifié",
    changer: "Changer de numéro",
    verifierTitre: "Vérifiez votre numéro pour commander",
    verifierTexte: "Nous vous envoyons un code à 6 chiffres sur WhatsApp. La boutique vous contactera sur ce numéro.",
  },
  connexion: {
    titre: "Se connecter",
    sousTitre: "Pour commander et suivre vos commandes",
    lienInvalide: "Ce lien de connexion est invalide, expiré ou déjà utilisé. Demandez un nouveau lien.",
    avecEmail: "Se connecter avec un e-mail (compte déjà créé par e-mail)",
    avecNumero: "Se connecter avec mon numéro de téléphone",
    email: "Adresse e-mail",
    emailAide: "Recevez un lien pour vous connecter sans mot de passe.",
    emailRecevoir: "Recevoir mon lien de connexion",
    envoi: "Envoi en cours…",
    emailInvalide: "Saisissez une adresse e-mail valide.",
    antiRobot: "Cochez d’abord le contrôle anti-robot.",
    emailEnvoye: "Un lien de connexion vous a été envoyé par e-mail",
    emailImpossible: "Impossible d’envoyer le lien de connexion. Réessayez dans quelques instants.",
  },
  code: {
    numero: "Numéro de mobile",
    aide: "Mobile algérien uniquement (05, 06 ou 07). Vous recevez un code à 6 chiffres sur WhatsApp.",
    recevoir: "Recevoir le code sur WhatsApp",
    envoi: "Envoi en cours…",
    antiRobot: "Cochez d’abord le contrôle anti-robot ci-dessous.",
    envoiImpossible: "Impossible d’envoyer le code. Vérifiez votre connexion et réessayez.",
    envoye: "Code envoyé au {numero}.",
    code: "Code à 6 chiffres",
    valider: "Valider le code",
    verification: "Vérification…",
    changer: "Changer de numéro ou recevoir un nouveau code",
    saisir: "Saisissez les 6 chiffres du code reçu.",
    verificationImpossible: "Impossible de vérifier le code. Vérifiez votre connexion et réessayez.",
  },
  commandes: {
    titre: "Mes commandes",
    aucune: "Vous n’avez pas encore de commande.",
    voirArticles: "Voir les articles",
    chargementImpossible: "Impossible de charger vos commandes. Réessayez.",
    commandeImpossible: "Impossible de charger la commande. Réessayez.",
    numero: "Commande n° {n}",
    statuts: { demandee: "Demandée", confirmee: "Confirmée", prete: "Prête", recuperee: "Récupérée", annulee: "Annulée", expiree: "Expirée" },
    titresSuivi: { demandee: "Commande envoyée", confirmee: "Confirmée par la boutique", prete: "Prête à récupérer", recuperee: "Récupérée", annulee: "Annulée", expiree: "Expirée" },
    motifs: { plus_en_stock: "Plus en stock", boutique_indisponible: "Boutique indisponible", client_a_annule: "Annulée par le client", autre: "Autre" },
    suivi: "Suivi de la commande",
    aVenir: " (à venir)",
    aRecuperer: "À récupérer avant le",
    motif: "Motif : {motif}",
    expiree: "Commande non récupérée dans les 24 heures : elle compte comme un no-show.",
    articles: "Articles commandés",
    total: "Total",
    note: "Votre note : « {note} »",
    ecrire: "Écrire à la boutique sur WhatsApp",
    voirBoutique: "Voir la boutique",
    mention: "Paiement en boutique · Annulation possible tant que la commande n’est pas prête",
    annuler: "Annuler ma commande",
    motAnnulation: "Un mot pour la boutique (facultatif)",
    confirmerAnnulation: "Confirmer l’annulation",
    retour: "Retour",
  },
  noShows: {
    titre: "Commandes non récupérées ({n})",
    explication: "La boutique a signalé que vous n’êtes pas venu(e). Si c’est une erreur, contestez dans les {jours} jours : la commande ne compte plus tant qu’OranPromo n’a pas décidé (un compte déjà bloqué le reste jusqu’à cette décision). Une seule contestation à la fois.",
    enExamen: "Contestation en cours d’examen",
    refusee: "Contestation refusée : la commande compte",
    votreMotif: "Votre motif : {motif}",
    delaiDepasse: "Délai de contestation dépassé ({jours} jours).",
    attendre: "Vous pourrez contester celle-ci quand OranPromo aura répondu à votre contestation en cours.",
    contester: "Contester",
    pourquoi: "Pourquoi contestez-vous ?",
    envoi: "Envoi…",
    envoyer: "Envoyer la contestation",
    fermer: "Fermer",
  },
};

export type Textes = typeof fr;
